/*
 * Copyright (c) 2000, 2020, Oracle and/or its affiliates.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at
 * http://oss.oracle.com/licenses/upl.
 */

package com.tangosol.run.component;


/**
* The ComponentPeer interface is the "signature" for all JavaBean "feeds"
* generated by AbstractBean integration model 
* (i.e. Component.GUI.Control.__Component)
*
* @version 1.00, 10/25/99
* @author 	Gene Gleyzer
*/
public interface ComponentPeer
    {
    /**
    * Retrieves the Component peer for this JavaBean integratee
    *
    * Note: the returned object is actually a Component, but since
    * its package is unknow (relocatable), we cannot specify it more precisely
    */
    public Object get_ComponentPeer();
    }
