///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Coherence Java gRPC Client

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Coherence Java gRPC Client

The Coherence Java gRPC Client is a library that allows a Java application to connect to a Coherence gRPC proxy server.

=== Usage

In order to use Coherence gRPC client, you need to declare it as a dependency in your `pom.xml`.
There also needs to be a corresponding Coherence server running the gRPC proxy for the client to connect to.

[source,xml,subs="attributes+"]
----
    <dependency>
        <groupId>{coherence-maven-group-id}</groupId>
        <artifactId>coherence-java-client</artifactId>
        <version>{version-coherence-maven}</version>
    </dependency>
----

== Access Coherence Resources

The simplest way to access remote Coherence resources, such as a `NamedMap` when using the gRPC client is via a
Coherence `Session`.

=== Obtain a Remote Session

Client gRPC sessions to can be configured using system properties. By default, if no properties are provided a gRPC session named `default` will be configured to connect to `localhost:1408`.

For example, the code below will create a gRPC `Session` named `default`:
[source,java]
----
import com.oracle.coherence.client.GrpcSessionConfiguration;
import com.tangosol.net.Session;
import com.tangosol.net.SessionConfiguration;

SessionConfiguration config = GrpcSessionConfiguration.builder().build();
Session session = Session.create(config);

NamedMap<String, String> map = session.getMap("foo");
----

=== Named gRPC Sessions

Client sessions can be named, by providing a name to the configuration builder:
For example, the code below will create a gRPC `Session` named `foo`:
[source,java]
----
import com.oracle.coherence.client.GrpcSessionConfiguration;
import com.tangosol.net.Session;
import com.tangosol.net.SessionConfiguration;

SessionConfiguration config = GrpcSessionConfiguration.builder("foo").build();
Session session = Session.create(config);

NamedMap<String, String> map = session.getMap("foo");
----


=== Session Configuration via Properties

Client gRPC sessions can be configured using system properties.
The system property names follow the format `coherence.grpc.channels.<name>.xyz`, where `<name>` is replaced with the session name.

For example the property to set the the port to connect to is `coherence.grpc.channels.<name>.port`, so to configure the port for the default session to 9099, set the property `-Dcoherence.grpc.channels.default.port=9099`

|===
|Property |Description

|`coherence.grpc.channels.<name>.host`
|The host name to connect to

|`coherence.grpc.channels.<name>.port`
|The port to connect to

|`coherence.grpc.channels.<name>.target`
|As an alternative to setting the host and port, setting target creates a channel using the `ManagedChannelBuilder.forTarget(target);` method (see the gRPC Java documentation).
|===
(replace `<name>` with the session name being configured).

=== Using TLS

By default, the `Channel` used by the gRPC session will be configured as a plain text connection.
TLS can be configured by setting the required properties.

|===
|Property |Description

|`coherence.grpc.channels.<name>.credentials`
|Set to one of `plaintext`, `insecure` or `tls`. The default is `plaintext` and will create an insecure plain text channel. Using `insecure` will enable TLS but not verify the server certificate (useful in testing). Using `tls` will enable TLS on the client.

|`coherence.grpc.channels.<name>.tls.ca`
|The location of a CA file if required to verify the server certs.
|===
(replace `<name>` with the session name being configured).

If the server has been configured for mutual verification the client's key and certificate can also be provided:

|===
|Property |Description

|`coherence.grpc.channels.<name>.tls.cert`
|The location of a client certificate file.

|`coherence.grpc.channels.<name>.tls.key`
|The location of a client key file.

|`coherence.grpc.channels.<name>.tls.password`
|The optional password for the client key file.
|===
(replace `<name>` with the session name being configured).


=== Create a Session with a Custom Channel

If a fully custom channel configuration is required application code can configure the session with a `Channel`.

[source,java]
----
Channel channel = ManagedChannelBuilder.forAddress("localhost", 1408)
                                       .usePlaintext()
                                       .build();

SessionConfiguration config = GrpcSessionConfiguration.builder(channel)
        .named("foo")
        .build();

Session session = Session.create(config);

NamedMap<String, String> map = session.getMap("foo");
----

The example above creates a simple gRPC channel to connect to `localhost:1408`.
A `Session` has been created with this channel by specifying the `GrpcSessions.channel(channel)` option.

Calls to `Session.create()` with the same parameters, in this case channel, will return the same `Session` instance.
Most gRPC `Channel` implementations do not implement an `equals()` method, so the same `Session` will only be returned for the exact same `Channel` instance.

==== Close a Session

When client code has finished with a `Session` it can be closed to free up and close any gRPC requests that are still
open by calling the `session.close()` method. This will also locally release (but not destroy) all Coherence resources
manged by that `Session`.

=== Specify a Serializer

The `Serializer` used by the remote session will default to Java serialization, unless the system property
`coherence.pof.enabled` is set to `true`, in which case POF will be used for the serializer.
The serializer for a session can be set specifically when creating a `Session`.

[source,java]
----
Serializer serializer = new JsonSerializer();
String format = "json";

SessionConfiguration config = GrpcSessionConfiguration.builder()
        .withSerializer(serializer, format)
        .build();

Session session = Session.create(config);
----

In the example above a json serializer is being used. The `GrpcSessions.serializer(ser, format)` session option is used
to specify the serializer and its format name. The format name will be used by the server to select the correct server
side serializer to process the session requests and responses.

NOTE: The serializer format configured must also have a compatible serializer available on the server so that the server
can deserialize message payloads.

=== Specify a Scope Name

In most cases a Coherence server only has a single `ConfigurableCacheFactory`, but it is possible to run multiple and
hence multiple different cache services managed by a different `ConfigurableCacheFactory`.
Typically, a scope name will be used to isolate different `ConfigurableCacheFactory` instances.

A gRPC client session can be created for a specific server side scope name by specifying the scope as an option when
creating the session.

[source,java]
----
SessionConfiguration config = GrpcSessionConfiguration.builder()
        .withScopeName("foo")
        .build();

Session session = Session.create(config);
----

In the example above the `GrpcSessions.scope("foo")` option is used to specify that the `Session` created should connect to resources on the server managed by the server side `Session` with the scope `foo`.
