///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2020, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Coherence Java gRPC Client

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Coherence Java gRPC Client

The Coherence Java gRPC Client is a library that allows a Java application to connect to a Coherence gRPC proxy server.

=== Usage

In order to use Coherence gRPC client, you need to declare it as a dependency in your `pom.xml`.
There also needs to be a corresponding Coherence server running the gRPC proxy for the client to connect to.

[source,xml,subs="attributes+"]
----
    <dependency>
        <groupId>{coherence-maven-group-id}</groupId>
        <artifactId>coherence-java-client</artifactId>
        <version>{version-coherence-maven}</version>
    </dependency>
----

== Access Coherence Resources

The simplest way to access remote Coherence resources, such as a `NamedMap` when using the gRPC client is via a
Coherence `Session`.

=== Obtain a Remote Session

To obtain a `Session` that connects to a remote gRPC proxy the first requirement is a gRPC `Channel`.
The client application must create the gRPC `Channel` with the required configuration corresponding to that
required by the server (for example any security settings etc).

The `Channel` can then be used to create a `Session` using the Coherence `Session` factory methods.
The `Session` can ten be used to access remote resources.

[source,java]
----
Channel channel = ManagedChannelBuilder.forAddress("localhost", 1408)
                                       .usePlaintext()
                                       .build();

Session session = Session.create(GrpcSessions.channel(channel));

NamedMap<String, String> map = session.getMap("foo");
----

The example above creates a simple gRPC channel to connect to `localhost:1408`.
A `Session` has been created with this channel by specifying the `GrpcSessions.channel(channel)` option.
The `Session` can used as a normal Coherence `Sessions` to create, maps, caches and topics.

Calls to `Session.create()` with the same parameters, in this case channel, will return the same `Session` instance.
Most gRPC `Channel` implementations do not implement an `equals()` method so the same `Session` will only be returned
for the exact same `Channel` instance.

==== Close a Session

When client code has finished with a `Session` it can be closed to free up and close any gRPC requests that are still
open by calling the `session.close()` method. This will also locally release (but not destroy) all Coherence resources
manged by that `Session`.

=== Specify a Serializer

The `Serializer` used by the remote session will default to Java serialization, unless the system property
`coherence.pof.enabled` is set to `true`, in which case POF will be used for the serializer.
The serializer for a session can be set specifically when creating a `Session`.

[source,java]
----
Channel channel = ManagedChannelBuilder.forAddress("localhost", 1408)
                                       .usePlaintext()
                                       .build();

Serializer ser = new JsonSerializer();
String format = "json";

Session session = Session.create(GrpcSessions.channel(channel),
                                 GrpcSessions.serializer(ser, format));
----

In the example above a json serializer is being used. The `GrpcSessions.serializer(ser, format)` session option is used
to specify the serializer and its format name. The format name will be used by the server to select the correct server
side serializer to process the session requests and responses.

NOTE: The serializer format configured must also have a compatible serializer available on the server so that the server
can deserialize message payloads.

=== Specify a Scope Name

In most cases a Coherence server only has a single `ConfigurableCacheFactory`, but it is possible to run multiple and
hence multiple different cache services managed by a different `ConfigurableCacheFactory`.
Typically, a scope name will be used to isolate different `ConfigurableCacheFactory` instances.

A gRPC client session can be created for a specific server side scope name by specifying the scope as an option when
creating the session.

[source,java]
----
Channel channel = ManagedChannelBuilder.forAddress("localhost", 1408)
                                       .usePlaintext()
                                       .build();

Session session = Session.create(GrpcSessions.channel(channel),
                                 GrpcSessions.scope("foo"));
----

In the example above the `GrpcSessions.scope("foo")` option is used to specify that the `Session` created should
connect to resources on the server managed by the `ConfigurableCacheFactory` with the scope `foo`.
