///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= POF Maven Plugin

== POF Maven Plugin

The POF Maven Plugin provides automated instrumentation of classes with the `@PortableType` annotation
to generate consistent (and correct) implementations of Evolvable POF serialization methods.

It is a far from a trivial exercise to manually write serialization methods that support serializing
inheritance hierarchies that support the `Evolvable` concept. However, with static type analysis these methods
can be deterministically generated.

This allows developers to focus on business logic rather than implementing boilerplate code for the
above-mentioned methods.

NOTE: Please see xref:docs/core/04_portable_types.adoc[Portable Types] documentation for more information and detailed instructions on Portable Types creation and usage.

== Usage

In order to use the POF Maven Plugin, you need to declare it as a plugin dependency in your `pom.xml`:

[source,xml,subs="attributes+"]
----
  <build>
    <plugins>
      <plugin>
        <groupId>{coherence-maven-group-id}</groupId>
        <artifactId>pof-maven-plugin</artifactId>
        <version>{version-coherence-maven}</version>
        <executions>
          <execution>
            <id>instrument</id>
            <goals>
              <goal>instrument</goal>
            </goals>
          </execution>
          <execution>
            <id>instrument-tests</id>
            <goals>
              <goal>instrument-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
----

An example `Person` class (below) when processed with the plugin is below
results in the bytecode shown below.

[source,java]
----
@PortableType(id=1000)
public class Person
    {
    public Person()
        {
        }

    public Person(int id, String name, Address address)
        {
        super();
        this.id = id;
        this.name = name;
        this.address = address;
        }

    int id;
    String name;
    Address address;

    // getters and setters omitted for brevity
    }
----

Generated bytecode:

[source,bash]
----
$ javap Person.class
Compiled from "Person.java"
public class demo.Person implements com.tangosol.io.pof.PortableObject,com.tangosol.io.pof.EvolvableObject {
  int id;
  java.lang.String name;
  demo.Address address;
  public demo.Person();
  public demo.Person(int, java.lang.String, demo.Address);
  public int getId();
  public void setId(int);
  public java.lang.String getName();
  public void setName(java.lang.String);
  public demo.Address getAddress();
  public void setAddress(demo.Address);
  public java.lang.String toString();
  public int hashCode();
  public boolean equals(java.lang.Object);

  public void readExternal(com.tangosol.io.pof.PofReader) throws java.io.IOException;   # <1>
  public void writeExternal(com.tangosol.io.pof.PofWriter) throws java.io.IOException;  # <1>
  public com.tangosol.io.Evolvable getEvolvable(int);                                   # <1>
  public com.tangosol.io.pof.EvolvableHolder getEvolvableHolder();                      # <1>
}
----

<1> Additional methods generated by Coherence POF plugin.
