///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2020, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Boot-Strapping Coherence
:description: Boot-Strapping a Coherence application
:keywords: coherence, java, documentation

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Boot-Strapping Coherence

Coherence has a simple boot-strap API that allows a Coherence application to be configured and started by
building a `com.tangol.net.Coherence` instance and starting it.
The `Coherence` instance provides access to one or more `com.tangosol.net.Session` instances.
A `com.tangosol.net.Session` gives access to Coherence clustered resources, such as `NamedMap`, `NamedCache`,
`NamedTopic` etc.
Sessions can be of different types, for example a session can be related to a `ConfigurableCacheFactory`,
itself configured from a configuration file, or a session might be a client-side gRPC session.

An example of some application boot-strap code might look like this:
[source,java]
----
// Create a Session configuration                                <1>
SessionConfiguration session = SessionConfiguration.builder()
        .named("Carts")
        .withConfigUri("cache-config.xml")
        .build();

// Create a Coherence instance configuration                     <2>
CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .withSession(SessionConfiguration.defaultSession())
        .withSession(session)
        .build();

// Create the Coherence instance from the configuration
Coherence coherence = Coherence.create(cfg);                     <3>

// Start Coherence
coherence.start();                                               <4>
----

<1> A `SessionConfiguration` is created. In this case the `Session` will be named `Carts` and will be created
from the `cache-config.xml` configuration file.
<2> A `CoherenceConfiguration` is created to configure the `Coherence` instance. This configuration contains
the default `Session` configuration and the `Carts` session configuration.
<3> A `Coherence` instance is created from the `CoherenceConfiguration`
<4> The `Coherence` instance is started.

The steps above are covered in more detail below.


=== Session Configurations

A `SessionConfiguration` is created by using the `SessionConfiguration` builder as shown in the example above.

==== Session Name

All sessions have a name that must be unique within the application. If a name has not been specified when the
`SessionConfiguration` is built the default name of `$Default$` will be used.

For example, this configuration will have the default name.
[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .build();
----

This configuration will have the name `Test`.
[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .name("Test")
        .build();
----

==== Session Configuration URI

The most common type of session is a wrapper around a `ConfigurableCacheFactory`.
When using the `SessionConfiguration` builder the configuration file URI is specified using the `withConfigUri()`
method, that takes a string value specifiying the configuration file location.

[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .withConfigUri("cache-config.xml")
        .build();
----

The example above uses a configuration file a named `cache-config.xml`.

If a configuration URI is not specified then the default value will be used. This value is `coherence-cache-config.xml`
unless this has been overridden with the `coherence.cacheconfig` System property.

==== Session Event Interceptors

Coherence provides many types of events, examples of a few would be life-cycle events for Coherence itself,
cache life-cycle events, cache entry events, partition events etc.
These events can be listened to by implementing an `EventInterceptor` that receives specific types of event.
Event interceptors can be registered with a `Session` as part of its configuration.

For example, suppose there is an interceptor class in the application called `CacheInterceptor` that listens to
`CacheLifecycleEvent` when caches get created or destroyed. This interceptor can be added to the session as shown
below:
[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .withInterceptor(new CacheInterceptor())
        .build();
----

The interceptor will receive cache life-cycle events for all caches created using the session.

==== Session Scope

Scope is a concept that has been in Coherence for quite a while that allows services to be scoped and hence isolated
from other services with the same name. For example multiple `ConfigurableCacheFactory` instances could be loaded
from the same XML configuration file but given different scope names so that each CCF will have its own services
in the cluster.

Unless multiple Sessions are required, a scope will not generally be used in a configuration.

A scope for a session can be configured using the configuration's `withScopeName()` method, for example:

[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .withScopeName("Test")
        .build();
----

The session (and any `ConfigurableCacheFactory` it wraps) created from the configuration above will have a scope name
of `Test`.

If no scope name is set in the `SessionConfiguration` then the session will have a scope that matches the session name.
If the session uses the default name then the scope name will also be the default scope.

[NOTE]
====
It is possible to set a scope name in the `<defaults>` section of the XML configuration file.
[source,xml]
.scoped-configuration.xml
----
<?xml version="1.0"?>
<cache-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-cache-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-cache-config coherence-cache-config.xsd">

  <defaults>
    <scope-name>Test</scope-name>
  </defaults>
----
A `ConfigurableCacheFactory` created from the XML above, and hence any `Session` that wraps it will have a scope
of `Test`.

When using the boot-strap API any scope name specifically configured in the `SessionConfiguration`
(that is not the default scope name) will override the scope name in the XML file.

For example, using the `scoped-configuration.xml` file above:

In this case the scope name will be `Foo` because the scope name has been explicitly set in the `SessionConfiguration`.
[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .withConfigUri("scoped-configuration.xml")
        .withScopeName("Foo")
        .build();
----

In this case the scope name will be `Foo` because although no scope name has been explicitly set in
the `SessionConfiguration`, the name has been set to `Foo`, so the scope name will default to `Foo`.
[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .named("Foo")
        .withConfigUri("scoped-configuration.xml")
        .build();
----

In this case the scope name will be `Test` as no scope name or session name has been explicitly set in
the `SessionConfiguration` so the scope name of `Test` will be used from the XML configuration.
[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .withConfigUri("scoped-configuration.xml")
        .build();
----

In this case the scope name will be `Test` as the session name has been set to `Foo` but the scope name has been
explicitly set to the default scope name using the constant `Coherence.DEFAULT_SCOPE` so the scope name
of `Test` will be used from the XML configuration.
[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .named("Foo")
        .withScopeName(Coherence.DEFAULT_SCOPE)
        .withConfigUri("scoped-configuration.xml")
        .build();
----



====


=== Coherence Configuration

A Coherence application is started by creating a `Coherence` instance from a `CoherenceConfiguration`.
An instance of `CoherenceConfiguration` is created using the builder. For example:

[source,java]
----
CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .build();
----

==== Adding Sessions

A `Coherence` instance manages one or more `Session` instances, which are added to the `CoherenceConfiguration` by
adding the `SessionConfiguration` instances to the builder.

If no sessions have been added to the builder the `Coherence` instance will run a single `Session` that uses the default
configuration file.

[source,java]
----
CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .build();
----

The configuration above will configure a `Coherence` instance with the default name and with a single `Sessions`
that wil use the default configuration file.

The default session can also be explicitly added to the `CoherenceConfiguration`:
[source,java]
----
CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .withSession(SessionConfiguration.defaultSession())
        .build();
----

As already shown, other session configurations may also be added to the `CoherenceConfiguration`:
[source,java]
----
SessionConfiguration session = SessionConfiguration.builder()
        .named("Carts")
        .withConfigUri("cache-config.xml")
        .build();

CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .withSession(session)
        .build();
----

Whilst there is no limit to the number of sessions that can be configured the majority of applications would only ever
require a single session - more than likely just the default session.


==== Coherence Instance Name

Each `Coherence` instance must be uniquely named. A name can be specified using the `named()` method on the builder,
if no name has been specified the default name of `$Default$` will be used.

In the majority of use-cases an application would only ever require a single `Coherence` instance so there would be
no requirement to specify a name.

[source,java]
----
CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .named("Carts")
        .build();
----

The configuration above will create a `Coherence` instance with the name `Carts`.

==== Add Global Event Interceptors

As already mentioned, event interceptors can be added to a `SessionConfiguration` to receive events for a session.
Event interceptors can also be added to the `Coherence` instance to receive events for all `Session` instances
managed by that `Coherence` instance.

For example, reusing the previous `CacheInterceptor` class, but this time for caches in all sessions:
[source,java]
----
SessionConfiguration cartsSession = SessionConfiguration.builder()
         .named("Carts")
         .withConfigUri("cache-config.xml")
         .build();

CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .withSession(SessionConfiguration.defaultSession())
        .withSession(cartsSession)
        .withInterceptor(new CacheInterceptor())
        .build();
----

Now the `CacheInterceptor` will receive events for both the default session and the `Certs` session.


=== Create a Coherence Instance

Once a `CoherenceConfiguration` has been created it can be used to create a `Coherence` instance.

[source,java]
----
CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .build();

Coherence coherence = Coherence.create(cfg);
----

The above example creates a default `Coherence` instance.

=== Start Coherence

After creating a `Coherence` instance it must be started to start all the sessions that the `Coherence` instance
is managing. This is done by calling the `start()` method.

[source,java]
----
Coherence coherence = Coherence.create(cfg);

coherence.start();
----

=== Obtaining a Coherence Instance

To avoid having to pass around the instance of `Coherence` that was used to boot-strap an application the
`Coherence` class has some static methods that make it simple to retrieve an instance.

If only a single instance of `Coherence` is being used in an application (which will cover most use-cases) then
the `getInstance()` method can be used:
[source,java]
----
Coherence coherence = Coherence.getInstance();
----

It is also possible to retrieve an instance by name:
[source,java]
----
CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .named("Carts")
        .build();

Coherence.create(cfg);
----
...then later...
[source,java]
----
Coherence coherence = Coherence.getInstance("Carts");
----

=== Ensuring Coherence Has Started

If application code needs to ensure that a `Coherence` instance has started before doing some work then the
`whenStarted()` method can be used to obtain a `CompletableFuture` that will be completed when the `Coherence`
instance has started.

[source,java]
----
Coherence               coherence = Coherence.getInstance("Carts");
CompletableFuture<Void> future    = coherence.whenStarted();

future.join();
----

There is also a corresponding `whenStopped()` method that returns a future that will be completed when the
`Coherence` instance stops.

=== Coherence Lifecycle Interceptors

Besides using the future methods described above it is possible to add and `EventInterceptor` to the configuration
of a `Coherence` instance that will receive life-cycle events.

Below is an example interceptor that implements `Coherence.LifecycleListener`.
[source,java]
----
public class MyInterceptor implements Coherence.LifecycleListener {
    public void onEvent(CoherenceLifecycleEvent event) {
        // process event
    }
}
----

The interceptor can be added to the configuration:
[source,java]
----
CoherenceConfiguration cfg = CoherenceConfiguration.builder()
        .withSession(SessionConfiguration.defaultSession())
        .withInterceptor(new MyInterceptor())
        .build();
----

When a `Coherence` instance created from this configuration is start or stopped the `MyInterceptor` instance will
receive events.
