///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2025, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Topics
:description: Coherence Core Improvements - Topics
:keywords: coherence, java, documentation, topics

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Topics

The main documentation on Coherence topics can be found in the commercial Coherence documentation
 {commercial-docs-base-url}/develop-applications/using-topics.html[Using Topics] section.
The documentation below covers new features added to topics since the latest commercial release.

=== Remote Topics

Coherence topics can be used from Extend and gRPC clients.
Coherence topics running on a client use remote topic services to communicate with a proxy on the server.
A remote topic is configured in the cache configuration file the same way as caches are configured.

A remote topic is specialized topic service that routes operations to a topic on the Coherence cluster. The remote topic and the topic on the cluster must have the same topic name. Extend clients use the NamedTopic interface as normal to get an instance of the topic. At run time, the topic operations are not executed locally but instead are sent using TCP/IP to an Extend or gRPC proxy service on the cluster. The fact that the topic operations are delegated to a topic on the cluster is transparent to the client code. There is no API difference between topics on a cluster member and topics on a client.

==== Defining a Remote Topic

In the cache configuration file, a remote topic is defined within the `<caching-schemes>` node using the `<remote-topic-scheme>` element for Extend clients or `<remote-grpc-topic-scheme>` element for gRPC clients.

The example below creates an Extend remote topic service that is named RemoteTopic and connects to the name service, which then redirects the request to the address of the requested proxy service. The use of the name service simplifies port management and firewall configuration.

[source,xml]
----
...
<topic-scheme-mapping>
   <topic-mapping>
      <cache-name>*</cache-name>
      <topic-name>extend-topic</scheme-name>
   </topic-mapping>
</topic-scheme-mapping>

<caching-schemes>
   <remote-topic-scheme>
      <scheme-name>extend-topic</scheme-name>
      <service-name>RemoteTopic</service-name>
   </remote-topic-scheme>
</caching-schemes>
...
----

The next example below creates a gRPC remote topic service that is named RemoteTopic and connects to the name service, which then redirects the request to the address of the requested gRPC proxy service. The use of the name service simplifies port management and firewall configuration.

[source,xml]
----
...
<topic-scheme-mapping>
   <topic-mapping>
      <cache-name>*</cache-name>
      <topic-name>grpc-topic</scheme-name>
   </topic-mapping>
</topic-scheme-mapping>

<caching-schemes>
   <remote-grpc-topic-scheme>
      <scheme-name>grpc-topic</scheme-name>
      <service-name>RemoteTopic</service-name>
   </remote-grpc-topic-scheme>
</caching-schemes>
...
----

=== Subscribing to Specific Channels

Data in a Coherence topic is partitioned into channels.
A full explanation of channels is given in the commercial documentation
{commercial-docs-base-url}/develop-applications/introduction-coherence-topics.html#GUID-8B389C21-BAD8-43DD-A08C-94162B575E37[About Channels] section.

By default, the server manages allocations of channels to subscribers to ensure that every channel is owned by a subscriber in a subscriber group. Each time a new subscriber subscribes to a group or unsubscribes from a group the channels are reallocated.

A new feature has been introduced to allow application code to manually decide which channel or channels a subscriber will subscribe to. This allows applications more control over assigning subscribers to channels but
with the caveat that it is then up to the application to ensure that the channels subscribed to correspond to the channels being published to otherwise a subscriber may not receive any messages or alternatively the messages
published by a publisher may never be received by a subscriber.

- If a subscriber is manually allocated channels then it will be allocated those channels and only those channels.
- If multiple subscribers in a subscriber group are manually allocated the same channels then only one of them will be assigned as the channel owner. Exactly which subscriber this will be is not deterministic. For example if Subscriber-A and Subscriber-B both try to subscriber to channel 1, then only one will own the channel. If it was Subscriber-A that was assigned ownership, then Subscriber-B would receive no messages from channel 1.
But, if Subscriber-A was closed, then channel 1 would be reassigned to Subscriber-B.
- It is possible to mix subscribers with manual allocations and subscribers with auto-allocations. For example if Subscriber-A was manually subscribed to channels 0, 1 and 2 and Subscriber-B had no manual allocations then Subscriber-B would automatically be assigned all the remaining channels.

A subscriber can be manually allocated channels using the `Subscriber.subscribeTo()` option when it is created.
For example:

A subscriber could subscribe to channel 1 as shown below:
[source,java]
----
Subscriber<MyMessage> subscriber = topic.createSubscriber(Subscriber.subscribeTo(1));
----

A subscriber could subscribe to multiple channels 0, 1, 3 and 16 as shown below:
[source,java]
----
Subscriber<MyMessage> subscriber = topic.createSubscriber(Subscriber.subscribeTo(0, 1, 3, 16));
----

[NOTE]
====
Any invalid channel numbers used in the `Subscriber.subscribeTo()` method will be ignored.
If all the channel identifiers passed to `Subscriber.subscribeTo()` are invalid the subscriber will not be subscribed to any channels.
====


=== Topics Resilience and Availability

On a cluster member topics are highly resilient and will continue to function during rolling upgrades of cluster members. As the topics API is generally asynchronous, API methods that publish to or subscribe to topics will continue to function, but will just take longer to complete. Publishing and subscribing on a cluster member can also survive the loss of all storage enabled members as the publish and subscribe operations will pause until storage members restart.

In an Extend or gRPC client, just like with caches, a client will reconnect if the proxy it is connected to dies, or it becomes disconnected for some other reason such as a network issue. This means that generally a topics operation will work as long as the client is able to reconnect to a proxy. Publishers and subscribers will attempt to connect behind the scenes for asynchronous calls, so these to would generally succeed. Where there may be issues or exceptions thrown is when a request is actually in-flight when the proxy connection fails. In this case, just like with caches, the caller will receive an exception, but the operation may still be executing on the cluster and may actually complete. For a publisher for example, the client may receive an exception and then has no knowledge whether a publish request was actually successful on the cluster. It is up to the application code to properly handle the `CompletableFuture` returned from asynchronous topic API calls and decide what action to take on errors.

==== Anonymous Subscribers

An anonymous subscriber is not durable and hence if disconnected from the cluster and later reconnects it may
miss messages that were previously unread or that were published while it was disconnected.

