///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Portable Types
:description: Coherence Portable Types
:keywords: coherence, serialization, pof, java, documentation

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Portable Types

https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/develop-applications/using-portable-object-format.html#GUID-F331E5AB-0B3B-4313-A2E3-AA95A40AD913[*Portable Object Format (POF)*] was first introduced in Coherence 3.2 (2006), as a way to serialize classes in a platform and language independent format, and is the only serialization format supported by the legacy non-Java Extend clients, such as .NET and C++ Extend client implementations.

As soon as it was released, POF became the preferred serialization format even for customers writing pure Java applications, for several reasons:

1. It is significantly faster than other supported serialization formats, such as Java serialization and `ExternalizableLite`.

2. It is significantly more compact that other supported serialization formats, allowing you to store more data in a cluster of a given size, and to move less data over the wire.

3. It supports seamless evolution of data classes, allowing you to upgrade various parts of the application (both storage members and clients) independently of one another, without the risk of losing data in the process.

Over the years POF remained largely unchanged, even though it did receive a number of additional features that simplified its use:

1. https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/develop-applications/using-portable-object-format.html#GUID-6E77D329-3A4F-4956-9412-BE34D727A772[*POF Reflection*] was introduced in Coherence 3.5 (2009), allowing users to extract individual attributes from the POF stream via `PofNavigator`.

2. https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/develop-applications/using-portable-object-format.html#GUID-0142E1B5-143A-404F-A961-F41340C5921D[*POF Annotations*] were introduced in Coherence 3.7.1 (2011), as a way to eliminate the need for the manual implementation of the serialization-related code.

Unfortunately, the latter fell a bit short. The implementation was heavily dependent on Java reflection, which sacrificed some performance benefits of POF. More importantly, they provide no support for class evolution, thus sacrificing another important POF benefit.

As such, POF Annotations were deemed somewhat inadequate, and we started working on their replacement in 2013. Some supporting features, such as _schema support_, were included in Coherence 12.2.1 (2015) and 14.1.1 (2020), and the remaining work was completed and released as part of the Coherence CE 20.12 release and will be available in the next commercial release.

=== Features and Benefits

*Portable Types* provide a way to add support for POF serialization to your classes via annotations and without the need to implement serialization code by hand, just like POF Annotations did.

However, unlike POF Annotations, Portable Types:

1. Implement serialization code at compile-time using byte code instrumentation, and do not rely on Java reflection at runtime at all. This makes them just as fast, but less error-prone, as manually implemented serialization code.

2. Support, _but do not require_ explicit registration via POF config file, as all the metadata required for POF type registration, such as type identifier, and the serializer class to use, are already available in the `@PortableType` annotation.

3. Fully support class evolution.

As a matter of fact, Portable Types provide a better and more complete evolution support than if you implemented `Evolvable` interface by hand.

One of the limitations of `Evolvable` is that it only supports evolution of the leaf classes in the class hierarchy.
Portable Types do not have this limitation, and allow you not only to evolve any class in the hierarchy, but also to evolve the class hierarchy itself, by adding new classes to any level of the class hierarchy.

When we first introduced POF back in 2006, it was never the goal to require manual implementation of the serialization code -- we always wanted to provide the tooling that would do the heavy lifting and allow users to simply express their intent via annotations. It may have taken us almost 15 years, but we feel that with the release of Portable Types, we are finally there.

=== Usage Basics

There are only two basic requirements for Portable Types:

1. The class must be annotated with `@PortableType` annotation, and

2. The fields that should be serialized must be annotated with `@Portable` or one of related annotations (`@PortableDate`, `@PortableArray`, `@PortableSet`, `@PortableList`, or `@PortableMap`)

[source,java]
----
@PortableType(id = 1)
public class Pet
    {
    @Portable
    protected String name;

    // constructors, accessors, etc.
    }

@PortableType(id = 2)
public class Dog extends Pet
    {
    @Portable
    private String breed;

    // constructors, accessors, etc.
    }
----

Additional attribute-level annotations allow you to control certain serialization behaviors that are specific to the type of the attribute.

For example, `@PortableDate` allows you to control whether you want to serialize date, time, or both when serializing `java.util.Date` instances (via `mode` property), and whether time zone information should be included (via `includeTimezone` property).

If you are using Java 8 (or later) `java.time` classes, that information can be derived from the class itself, so you can (and should) simply use `@Portable` annotation instead. For example, `LocalTime` will be serialized as time only, with no time zone information, while the `OffsetDateTime` will be serialized as both date and time, with time zone information.

Similarly, when serializing arrays, collections and maps, POF allows you to use _uniform encoding_, where the element type (or key and/or value type, in case of maps) is written into the POF stream only once, instead of once for each element of the collection, resulting in a more compact serialized form.

[source,java]
----
public class MyClass
    {
    @PortableArray(elementClass = String.class)
    private String[] m_stringArray;

    @PortableSet(elementClass = String.class, clazz = LinkedHashSet.class)
    private Set<String> m_setOfStrings;

    @PortableList(elementClass = String.class)
    private List<String> m_listOfStrings;

    @PortableMap(keyClass = Integer.class, valueClass = String.class, clazz = TreeMap.class)
    private Map<Integer, String> m_uniformMap;
    }
----

As you can see from the examples above, these annotations also allow you to specify the concrete class that should be created during deserialization for a given attribute. If the `clazz` property is not specified, `HashSet` will be used as a default set type, `ArrayList` as a default list type, and `HashMap` as a default map type.

=== Class Versioning and Evolution

Coherence is a distributed system, and there is no guarantee that every cluster member, and every client process that connects to the cluster, will have the same version of each and every class. As a matter of fact, for systems that use rolling upgrades in order to avoid any downtime, it is pretty much guaranteed that they won't!

It is also neither safe nor practical for most Coherence customers to upgrade the cluster and all the clients at the same time, so being able to tolerate different versions of the same class across cluster members and clients is not only nice to have, but a necessity for many Coherence users.

The issue is that when a process that has an older version of the class reads serialized data created from the newer version of the same class, it may encounter some attributes that it knows nothing about. Ideally, it should be able to ignore them and read the attributes it needs and knows about, instead of crashing, but that only solves part of the problem. If it ignores the unknown attributes completely, what will happen when it writes the same data back, by serializing an older version of the class that is only aware of some attributes? Unfortunately, the most likely answer is that it will lose the data it previously received but knows nothing about.

Obviously, this is not a desirable scenario for a system that is intended for long-term data storage, so POF supports class evolution in a way that ensures that no data will be lost, regardless of how many versions of the same class are present across the various cluster and client processes, and regardless of which of those processes read or write the data. The support for class evolution has been in POF from the very beginning, via the `Evolvable` interface, but Portable Types remove some of the limitations and make the whole process significantly simpler.

Both the class annotation (`@PortableType`) and the attribute annotations (`@Portable` and related annotations) provide a way to specify versioning information necessary for class evolution.

At the class level, whenever you modify a class by introducing a new attribute, you should increment the `version` property of the `@PortableType` annotation.

At the same time, you should specify `since` attribute that matches the new class version number for any new class attribute.
For example, to add `age` attribute to the `Pet` class, and `color` attribute to the `Dog` class, we would change the code above to:

[source,java]
----
@PortableType(id = 1, version = 1)
public class Pet
    {
    @Portable
    protected String name;

    @Portable(since = 1)
    protected int age;

    // constructors, accessors, etc.
    }

@PortableType(id = 2, version = 1)
public class Dog extends Pet
    {
    @Portable
    private String breed;

    @Portable(since = 1)
    private Color color;

    // constructors, accessors, etc.
    }
----

Notice that both `version` and `since` properties are zero-based, which allows you to omit them completely in the initial implementation. It also means that for the first subsequent revision they should be set to `1`.

Of course, those are just the defaults. You can certainly set the class and attribute version explicitly to any value even for the initial implementation, if you are so inclined. The only thing that matters is that you bump the version and set the `since` property to the latest version number whenever you make changes to the class in the future.

For example, if in the future we decide to add `height` and `weight` attributes to the `Pet` class, we would simply increment the `version` to `2` and set the `since` property for the new attributes accordingly:

[source,java]
----
@PortableType(id = 1, version = 2)
public class Pet
    {
    @Portable
    protected String name;

    @Portable(since = 1)
    protected int age;

    @Portable(since = 2)
    protected int height;

    @Portable(since = 2)
    protected int weight;

    // constructors, accessors, etc.
    }
----

[WARNING]
====================================
It may be obvious by now, but it's probably worth calling out explicitly: class evolution allows you to add attributes to the new version of the class, but you should *never* remove existing attributes, as that will break serialization across class versions.

You can certainly remove or deprecate attribute _accessors_ from the class, but you should leave the field itself as-is, in order to preserve backwards compatibility of the serialized form.

Along the same lines, you should avoid renaming the fields, as the default serialization order of fields is determined based on the alphabetical order of field names within a given class version (all fields with the same `since` value).
====================================

=== Compile-time Instrumentation

Annotating the classes is the first step in the implementation of Portable Types, but it is not sufficient on its own. In order to implement the necessary serialization logic, the classes also need to be instrumented at compile time.

This is accomplished using the `pof-maven-plugin`, which should be configured in your POM file:

[source,xml]
----
<plugin>
  <groupId>com.oracle.coherence.ce</groupId>
  <artifactId>pof-maven-plugin</artifactId>
  <version>20.12</version>
  <executions>
    <execution>
      <id>instrument</id>
      <goals>
        <goal>instrument</goal>
      </goals>
    </execution>
    <execution>
      <id>instrument-tests</id>
      <goals>
        <goal>instrument-tests</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

The configuration above will discover and instrument all project classes annotated with `@PortableType` annotation, including test classes. If you don't need to instrument test classes you can omit the `instrument-tests` execution from the plugin configuration.

The `pof-maven-plugin` uses `Schema` support to define the type system that contains all reachable portable types. This type system includes not only project classes that need to be instrumented, but also all portable types that exist in project dependencies. This is necessary because those dependent types may be used as attributes within the project classes, and need to be serialized appropriately.

In some cases it may be necessary to expand the type system with the types that are not annotated with `@PortableType` annotation, and are not discovered automatically. This is typically the case when some of your portable types have enum values, or existing classes that implement `PortableObject` interface explicitly as attributes.

You can add those types to the schema by creating a `META-INF/schema.xml` file and specifying them explicitly. For example, assuming the `Color` class from the code examples above is an enum type, you would need to create the following `META-INF/schema.xml` file to register it and allow `pof-maven-plugin` to instrument `Dog` class correctly:

[source,xml]
----
<?xml version="1.0"?>

<schema xmlns="http://xmlns.oracle.com/coherence/schema"
       xmlns:java="http://xmlns.oracle.com/coherence/schema/java"
       external="true">

  <type name="Color">
    <java:type name="petstore.Color"/>
  </type>

</schema>
----

Once all these bits and pieces are in place, you can simply run your build as usual:

[source,text]
----
$ mvn clean install
----

You can verify that the classes were instrumented successfully by checking the Maven output log. You should see something similar to the following:

[source,text]
----
[INFO] --- pof-maven-plugin:20.12:instrument (instrument) @ petstore ---
[INFO] Running PortableTypeGenerator for classes in /projects/petstore/target/classes
[INFO] Instrumenting type petstore.Pet
[INFO] Instrumenting type petstore.Dog
----

Once the classes are successfully instrumented, they are ready to be registered and used.

=== Registration and Discovery

Portable Object Format is not a self-describing serialization format: it replaces platform-specific class names with integer-based _type identifiers_, so it needs a way of mapping those type identifiers back to the platform-specific classes. This enables _portability_ across platforms, which was, as the name clearly says, the main objective of POF.

To manage the mappings between the type identifiers and concrete types, POF uses `com.tangosol.io.pof.PofContext`:

[source,java]
----
public interface PofContext extends Serializer
    {
    PofSerializer getPofSerializer(int nTypeId);

    int getUserTypeIdentifier(Object o);
    int getUserTypeIdentifier(Class<?> clz);
    int getUserTypeIdentifier(String sClass);

    String getClassName(int nTypeId);
    Class<?> getClass(int nTypeId);

    boolean isUserType(Object o);
    boolean isUserType(Class<?> clz);
    boolean isUserType(String sClass);
    }
----

It is worth noting that `PofContext` extends `com.tangosol.io.Serializer` interface, which means that any `PofContext` implementation can be used wherever Coherence expects a `Serializer` to be specified: within cache services as a storage-level serializer for data classes, as a transport-level serializer between thin clients and the proxy servers, etc. The `PofContext` performs the actual serialization by delegating to the appropriate `PofSerializer`, which is obtained via the `PofContext.getPofSerializer` method, based on a type identifier.

There are several built-in implementations of `PofContext`. The `SimplePofContext` allows you to programmatically register type mappings by providing all the metadata needed for serialization, such as type identifier, class, and the `PofSerializer` to use:

[source,java]
----
SimplePofContext ctx = new SimplePofContext();
ctx.registerUserType(1, Pet.class, new PortableTypeSerializer<>(1, Pet.class));
ctx.registerUserType(2, Dog.class, new PortableTypeSerializer<>(2, Dog.class));
ctx.registerUserType(3, Color.class, new EnumPofSerializer());
----

Notice that a lot of this information is somewhat repetitive and unnecessary when working with portable types, as all the metadata you need can be obtained from the class itself or the `@PortableType` annotation.

Because of that, `SimplePofContext` also provides several convenience methods, specifically for portable types:

[source,java]
----
ctx.registerPortableType(Pet.class);
ctx.registerPortableType(Dog.class);
----

Or even simpler:

[source,java]
----
ctx.registerPortableTypes(Pet.class, Dog.class);
----

While the `SimplePofContext` is useful for testing and quick prototyping, a `PofContext` implementation that is much more widely used within Coherence applications is `ConfigurablePofContext`.

The `ConfigurablePofContext` allows you to provide type mappings via an external XML file:

[source,xml]
----
<pof-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-pof-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-pof-config coherence-pof-config.xsd">

  <user-type-list>

    <user-type>
      <type-id>1</type-id>
      <class-name>petstore.Pet</class-name>
    </user-type>

    <user-type>
      <type-id>2</type-id>
      <class-name>petstore.Dog</class-name>
    </user-type>

    <user-type>
      <type-id>3</type-id>
      <class-name>petstore.Color</class-name>
      <serializer>
        <class-name>com.tangosol.io.pof.EnumPofSerializer</class-name>
      </serializer>
    </user-type>

  </user-type-list>

</pof-config>
----

You may notice that we didn't have to specify `serializer` explicitly for `Pet` and `Dog` classes. This is because `ConfigurablePofContext` has the logic to determine which of the built-in `PofSerializer` implementations to use depending on the interfaces implemented by, or the annotations present on the specified class. In this case, it will automatically use `PortableTypeSerializer` because the classes have `@PortableType` annotation.

However, we can make the configuration even simpler by enabling portable type discovery:

[source,xml]
----
<pof-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-pof-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-pof-config coherence-pof-config.xsd">

  <user-type-list>

    <user-type>
      <type-id>3</type-id>
      <class-name>petstore.Color</class-name>
      <serializer>
        <class-name>com.tangosol.io.pof.EnumPofSerializer</class-name>
      </serializer>
    </user-type>

  </user-type-list>

  <enable-type-discovery>true</enable-type-discovery>

</pof-config>
----

Once you set the `enable-type-discovery` flag to `true`, the `ConfigurablePofContext` will discover all the classes annotated with `@PortableType` and register them automatically, based on the annotation metadata. If we didn't have the `Color` enum that has to be registered explicitly, we could even omit the configuration file completely, as the default `pof-config.xml` file that is built into Coherence looks like this:

[source,xml]
----
<pof-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-pof-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-pof-config coherence-pof-config.xsd">

  <user-type-list>
    <!-- by default just include coherence POF user types -->
    <include>coherence-pof-config.xml</include>
  </user-type-list>

  <enable-type-discovery>true</enable-type-discovery>

</pof-config>
----

[NOTE]
=====================================
The portable type discovery feature depends on the availability of a https://github.com/wildfly/jandex[Jandex] index within the modules that provide portable types that need to be registered.

Make sure that you configure Jandex Maven Plugin to index classes in your modules at build time:

[source,xml]
----
<plugin>
  <groupId>org.jboss.jandex</groupId>
  <artifactId>jandex-maven-plugin</artifactId>
  <version>1.0.8</version>
  <executions>
    <execution>
      <id>make-index</id>
      <goals>
        <goal>jandex</goal>
      </goals>
      <phase>process-classes</phase>
    </execution>
  </executions>
</plugin>
----
=====================================

=== IDE Support

Once you have annotated, instrumented and registered portable types as described in the sections above, you can use them with Coherence just as easily as you would use plain Java `Serializable` classes, by configuring Coherence services to use `pof` serializer instead of the default `java` serializer.

However, there is still one problem: serialization code is implemented by the `pof-maven-plugin` at compile-time, and only if you run Maven build, which can make it a bit cumbersome to run unit and integration tests within your IDE.

In order to solve that problem, we have implemented IDE plugins for IntelliJ IDEA and Eclipse, which can instrument your classes during incremental or full compilation performed by your IDE. This allows you to test both the serialization of your classes and the code that depends on it without having to run Maven build or leave your IDE.

Please follow the documentation for the https://github.com/oracle/coherence-idea-plugin[Coherence IntelliJ Plugin] or https://github.com/oracle/coherence-eclipse-plugin[Coherence Eclipse Plugin] for detailed instructions on how to install and use the plugin for your favorite IDE.

[NOTE]
=====================================
We've used 1, 2, and 3 as type identifiers in the code and configuration examples above for simplicity, but it is worth noting that Coherence reserves type identifiers from 0 to 999 for internal use.

That means that you should only use type identifiers of 1000 or higher for your own classes.
=====================================