///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2022, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= POF Configuration Discovery
:description: Coherence POF
:keywords: coherence, serialization, pof, java, documentation

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== POF Configuration Discovery


=== Making POF Configuration Files Discoverable At Runtime

In Java applications where new modules may be added at deploy time or runtime, the full set of required POF configuration files may not be known ahead of time and hence it may not be possible to create a POF configuration file with all the correct `<include>` elements. To allow for this type of use case, it is possible to make POF configuration files discoverable at runtime by the ConfigurablePofContext class instead of needing to put them inside `<include>` elements.

To make a configuration file discoverable, create a class that implements `com.tangosol.io.pof.PofConfigProvider`.
The `PofConfigProvider` has a single method that must be implemented to return the name of the configuration file.
At runtime, the `ConfigurablePofContext` class uses the Java `ServiceLoader` to discover implementations of `PofConfigProvider`
and load their provided POF configuration files, exactly as if they had been added in `<include>` elements.

For example, the `RuntimeConfigProvider` class below provides `discovered-pof-config.xml` as the configuration file name.
At runtime, the `ConfigurablePofContext` class will load the `discovered-pof-config.xml` POF configuration file.

[source,java]
.RuntimeConfigProvider.java
----
package com.oracle.coherence.examples;

import com.tangosol.io.pof.PofConfigProvider;

public class RuntimeConfigProvider
        implements PofConfigProvider
    {
    @Override
    public String getConfigURI()
        {
        return "discovered-pof-config.xml";
        }
    }
----

To make the `RuntimeConfigProvider` class discoverable, either:

Add it to a file `META-INF/services/com.tangosol.io.pof.PofConfigProvider`

[source]
.META-INF/services/com.tangosol.io.pof.PofConfigProvider
----
com.oracle.coherence.examples.RuntimeConfigProvider
----

Or if using Java Modules, add it to the `module-info.java` file:

[source,java]
.module-info.java
----
module com.oracle.coherence.examples {
    provides com.tangosol.io.pof.PofConfigProvider
        with com.oracle.coherence.examples.RuntimeConfigProvider;
}
----

If required, a `PofConfigProvider` implementation may return multiple POF configuration files by overriding
the `PofConfigProvider.getConfigURIs()` method. In this case the singular `getConfigURI()` will not be called.

In the example below the `RuntimeConfigProvider` the `getConfigURIs()` method returns the POF configuration file names
`discovered-pof-config.xml`, `additional-pof-config.xml`, both of which will be loaded by the `ConfigurablePofContext`
at runtime.

[source,java]
.RuntimeConfigProvider.java
----
package com.oracle.coherence.examples;

import com.tangosol.io.pof.PofConfigProvider;

import java.util.Set;

public class RuntimeConfigProvider
        implements PofConfigProvider
    {
    @Override
    public Set<String> getConfigURIs()
        {
        return Set.of("discovered-pof-config.xml",
                "additional-pof-config.xml");
        }

    @Override
    public String getConfigURI()
        {
        return null;
        }
    }
----
