///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2023, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Secured Production Mode
:description: Coherence Core Improvements
:keywords: coherence, java, documentation

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Secured Production Mode

When Coherence is running in secured production mode, TLS/SSL is enabled for communication between cluster nodes, and between Coherence*Extend clients and proxy servers.

=== Enabling Coherence Secured Production Mode 

Prior to enable secured production mode, an SSL Socket Provider must be defined to be used by TCMP for communication between cluster nodes and by clients and proxies for Coherence*Extend. The global socket provider must also be set to use the SSL socket provider.  See the documentation on 
https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.2206/secure/using-ssl-secure-communication.html[Using SSL to Secure Communication].

To enable secured production mode, you can either configure it in the Coherence operational override file or use the system property, coherence.secured.production. By default, secured production mode is not enabled. If Coherence is running in development mode, the secured production mode setting is ignored.

You can configure secured production mode as follows:

[source,xml]
.operational-override.xml
----
<cluster-config>
  ...
  <global-socket-provider system-property="coherence.global.socketprovider">mySSL</global-socket-provider>
  <socket-providers>
    <socket-provider id="mySSL">
      <ssl>
      ...
      </ssl>
    </socket-provider>
  </socket-providers>
  ...
  <secured-production system-property="coherence.secured.production">true</secured-production>
</cluster-config>
----

The *coherence.secured.production* system property can also be used to enable secured production mode. For example, if an SSL socket provider, "mySSL", is defined in the operational override:
[source,bash]
-Dcoherence.global.socketprovider=mySSL -Dcoherence.secured.production=true

