///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Partition Events Logging
:description: Logging of events that render partitions unavailable
:keywords: coherence, partition, documentation

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Partition Events Logging

The most commonly used service in Coherence to store and access data is the distributed / partitioned service. It offers partitioned access to store and retrieve data, thus provides scalability, in addition to redundancy by ensuring replicas are in sync.

This concept of partitioning can be entirely opaque to an end user as Coherence will transparently map keys to partitions and partitions to members. As ownership members join and leave the partitioned service, the partitions are redistributed across the new/remaining members avoiding an entire rehash of the data. Coherence also designates replicas providing them an initial snapshot followed by a journal of updates as they occur on the primary.

These partition lifecycle events (members joining and leaving the service) result in partitions being blocked and therefore Coherence attempts to reduce this time of unavailability as much as possible. Until now, there has been minimal means to track this partition unavailability. This feature provides insight into these partition lifecycle events, highlighting when they start and end allowing customers to correlate increased response times with said lifecycle events.

=== Data Availability

In order to preserve the integrity of data, when partition events occur such as partition movements between members, read or write access to data will be temporarily blocked.
This happens when re-distribution takes place or indices are built. The amounts of time involved are usually extremely short, but can add up if the cache contains significant amounts of data.

[width="80%",cols="3,10",options="header"]
|====
|Event Type|Description
|Redistribution |When a server joins or leaves a cluster, a number of events occur on each member in the cluster, existing and new, which correspond to the movement of data and backup partitions according to the partitioning strategy. This scheme determines which members own which partitions, and which members own which backups.
|Restoring from backup |After primary partitions are lost, the backups are moved into primary storage in the members where they are located. Naturally, the partitions in question are locked until the event finishes.
|Recovery from persistence |Persistence maintenance, such as snapshot creation and recovery from persistence, will cause the affected partitions to be unavailable.
|Index building |If an application needs to have data indexed, this is typically done by calling `addIndex` on a `NamedCache`. If the cache already contains a significant amount of data, or the cost of computing the index per entry (the `ValueExtractor`) is high, this operation can take some time during which any submitted queries will be blocked waiting for the index data structures to be populated. Note that regular index maintenance, such as adding or deleting elements, does not incur the same unavailability penalty.
|====

=== Feature Usage

By default, logging of times when partitions are unavailable is turned off as it generates a significant amount of logs.

To enable logging of partition events, set the property `coherence.distributed.partition.events` to `log` and https://docs.oracle.com/en/middleware/standalone/coherence/{version-commercial-docs}/develop-applications/debugging-coherence.html#GUID-2C427606-5F61-4640-863F-20183E519E52[set log level] to 8 or more.

e.g.:

[source,text]
----
-Dcoherence.distributed.partition.events=log
----

=== Events Logged

The events below are logged, one per partition except when partitions are initially assigned. Along with that, the owning member and possibly the time it made the partition unavailable are also logged.

[width="80%",cols="3,10",options="header"]
|====
|Event|Description
|`ASSIGN` |The partition is either initially, or as a result of losing primary and all backups, assigned to a cluster member.
|`PRIMARY_TRANSFER_OUT` |The partition is being transferred to a different member.
|`BACKUP_TRANSFER_OUT` |This primary is transferring a snapshot of the partition and all its content to the targeted member as it will be in the chain of backup replicas.
|`PRIMARY_TRANSFER_IN` |This member is receiving a partition and all related data for primary ownership. This will be due to a `PRIMARY_TRANSFER_OUT` from the existing owner of the partition.
|`RESTORE` |The loss of primary partitions results in backup owners (replicas) restoring data from backup storage to primary for the affected partitions.
|`INDEX_BUILD` |Index data structures were populated for the relevant partitions. This will effect queries that use said indices but does not block key based data access or mutation.
|`PERSISTENCE` |The relevant partitions were made unavailable due to persistence maintenance operations; this will minimally include recovery from persistence and snapshot creation.
|====

=== Example

On Member 1:

(at startup)
----
2021-06-11 09:26:10.159/5.522 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=PartitionedTopicDedicated:0x000A:5, member=1): PartitionSet{0..256}, Owner: 1, Action: ASSIGN, UnavailableTime: 0
...
----

(application calls `addIndex()` on a cache)
----
2021-06-11 09:28:36.872/152.234 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=PartitionedCacheDedicated:0x000B:152, member=1): PartitionId: 43, Owner: 1, Action: INDEX_BUILD, UnavailableTime: 3
...
----

(the partitions listed are being transferred to another member, along with backups; note how backups and partitions are not the same)
----
2021-06-11 09:28:45.573/160.935 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=DistributedCache:PartitionedCache, member=1): PartitionId: 132, Owner: 1, Action: BACKUP_TRANSFER_OUT, UnavailableTime: 1
2021-06-11 09:28:45.678/161.040 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=DistributedCache:PartitionedCache, member=1): PartitionId: 133, Owner: 1, Action: BACKUP_TRANSFER_OUT, UnavailableTime: 1
...
2021-06-11 09:28:49.911/165.273 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=DistributedCache:PartitionedCache, member=1): PartitionId: 2, Owner: 1, Action: PRIMARY_TRANSFER_OUT, UnavailableTime: 5
2021-06-11 09:28:50.017/165.379 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=DistributedCache:PartitionedCache, member=1): PartitionId: 3, Owner: 1, Action: PRIMARY_TRANSFER_OUT, UnavailableTime: 3
...
----

On Member 2:

(partitions are being received; if they have indices, they are rebuilt immediately after reception)
----
2021-06-11 09:28:49.805/8.033 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=DistributedCache:PartitionedCache, member=2): PartitionId: 1, Owner: 2, Action: PRIMARY_TRANSFER_IN, UnavailableTime: 1
2021-06-11 09:28:49.806/8.034 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=PartitionedCacheDedicated:0x000B:8, member=2): PartitionId: 1, Owner: 2, Action: INDEX_BUILD, UnavailableTime: 0
----

Member 2 stops, back on Member 1:

(partitions are being restored from backup, and the indices related to them rebuilt)
----
2021-06-11 10:29:19.041/3794.322 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=DistributedCache:PartitionedCache, member=1): PartitionId: 0, Owner: 1, Action: RESTORE, UnavailableTime: 109
2021-06-11 10:29:19.041/3794.322 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=DistributedCache:PartitionedCache, member=1): PartitionId: 1, Owner: 1, Action: RESTORE, UnavailableTime: 109
...
2021-06-11 10:29:19.062/3794.343 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=PartitionedCacheDedicated:0x000E:3794, member=1): PartitionId: 1, Owner: 1, Action: INDEX_BUILD, UnavailableTime: 12
2021-06-11 10:29:19.066/3794.347 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=PartitionedCacheDedicated:0x000D:3794, member=1): PartitionId: 0, Owner: 1, Action: INDEX_BUILD, UnavailableTime: 16
2021-06-11 10:29:19.067/3794.349 Oracle Coherence GE 14.1.2.0.0 (dev-mycomputer) <D8> (thread=PartitionedCacheDedicated:0x000E:3794, member=1): PartitionId: 2, Owner: 1, Action: INDEX_BUILD, UnavailableTime: 5
...
----

=== Future

While logging gives valuable details on partition's lifecycle, it is a simple means of providing this information. Ultimately, better forms of presenting it for consumption will be provided, such as a JMX MBean or a Coherence report.
