///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2024, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Queues
:description: Coherence Core Improvements
:keywords: coherence, java, documentation

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Queues

Starting with Coherence CE 24.03, Coherence supports Queues as data structure.
The Coherence `NamedQueue` is an implementation of `java.util.Queue` and `NamedDeque` is and
implementation of `java.util.Deque`.

[IMPORTANT]
====
Coherence queues are mapped to caches with the same name as the queue.
If a cache is being used for a queue the same cache should not also be used as a normal data cache.
====

=== Blocking Queue

The Coherence Concurrent module contains an implementation of `java.util.concurrent.BlockingQueue` called `NamedBlockingQueue` and an implementation of `java.util.concurrent.BlockingDeque` called `NamedBlockingDeque`.

To use a Coherence blocking queue in your application you need to add a dependency on
the `coherence-concurrent` module.

[source,xml,subs="attributes+"]
----
    <dependency>
        <groupId>{coherence-maven-group-id}</groupId>
        <artifactId>coherence-concurrent</artifactId>
        <version>{version-coherence-maven}</version>
    </dependency>
----

To obtain an instance of a blocking queue use the `com.oracle.coherence.concurrent.Queues` factory class.

For example to obtain a `BlockingQueue` named "my-queue":

[source,java]
----
NamedBlockingQueue<String> queue = Queues.blocking("my-queue");
----

For example to obtain a `BlockingDeque` named "my-deque":

[source,java]
----
NamedBlockingDeque<String> queue = Queues.blockingDeque("my-deque");
----

The blocking queue implementations work by using Coherence events. When application code calls a blocking method, the calling thread will be blocked, the blocking is not on the server. The application code will become unblocked when it receives an event from the server.

For example, if application code calls the `NamedBlockingQueue` `take()` method, and the queue is empty, this method will block the calling thread. When an element is put into the queue by another thread (maybe on another JVM) the calling application will receive an event. This will retry the `take()` and if successful will return. If the retry of the `take()` is unsuccessful the calling thread remains blocked (for example another thread or another JVM was also blocked taking from the same queue and managed to get its retry in first.

Another example would be an application calling `NamedBlockingQueue` `put()` method, which will block when the queue is full (i.e. reaches the 2GB size limit). In this case the calling thread will be blocked until a delete event is received to signal that there is now space in the queue. The `put()` will be retried and if successful control returned to the calling thread. If the retry is unsuccessful the thread will remain blocked (for example another thread or JVM was also blocked on a `put()` and its retry succeeded and refilled the queue).

== Limitations

The current queue implementation in Coherence has some limitations detailed below.

This implementation of a queue does not scale the same way as a Coherence cache or a Coherence topic does. In the current queue implementation, all the data for the queue is stored in a single Coherence partition. This means that the total size of the elements in a single queue instance cannot be larger than 2GB. This is a limitation of Coherence where a partition for a cache cannot exceed 2GB, as that is the limit of the buffer size used to transfer data between cluster members. If Coherence queues allowed a partition to grow over 2GB, the queue would work fine up to the point where Coherence needed to transfer that partition to a new member on fail-over, at that point data would be lost.

The Coherence server will refuse to accept offers to the queue if its size will exceed 2GB.
The `java.util.Queue` contact allows for queues to reject offers, so this size limitation conforms to the queue contract. Application developers should check the response from offering data to the queue to determine whether the offer has succeeded or not.
We use the term "offer" here to cover all queue and deque methods that add data to the queue.
An alternative to checking the return boolean from an `offer()` call would be to use a `NamedBlockingQueue` where the `put()` method will block if the queue is full,

In normal operation queues should not get huge, this would usually mean that the processes reading from the queue are not keeping up with the processes writing to the queue. Application developers should obviously load test their applications using queues to ensure that they are not going to have issues with capacity.

Queue operations such as offering and polling will contend on certain data structures and this will limit the number of parallel requests and how fast requests can be processed. In order to maintain ordering, polling contends on either the head or tail entry, depending on which end of the queue is being polled. This means that poll methods can only be processed sequentially, so even though a poll is efficient and fast, a large number of concurrent poll requests will queue and be processed one at a time. Offer methods do not contend on the head or tail, but will contend on the atomic counters used to maintain the head and tail identifiers. So, whilst Coherence can process multiple offer requests on different worker threads, there will be minor contention on the `AtomicLong` updates.

Queue operations that work on the head and tail, such as offering and polling are efficient. Some of the other methods in `java.util.Queue` and `java.util.Deque` are less efficient, for example iterators, `retainAll()`, `removeAll()`, `contains()` etc, but these are not frequently used by applications that require basic queue functionality.




