///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Coherence Documentation Module

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Coherence Documentation Module

This is the module that builds the Coherence documentation.
The module is not part of the default build and must be built separately.

=== Build the Docs

To build the docs, run the following Maven command from the top-level `prj/` directory:

[source,shell]
----
mvn clean install -DskipTests -P docs -pl docs
----

=== View the Docs

To view the documentation to see what it looks like after building run the following command from the top-level `prj/` directory:

[source,shell]
----
mvn exec:exec -P docs -pl docs
----

Docs can be viewd at http://localhost:8080

NOTE: This requires Python to be installed and runs a small Python http server from the directory where the docs
have been built to.

== Version Numbers

When putting version numbers in `.adoc` files, we use attribute substitutions.
Attributes are set in the `sitegen.yaml` file, for example

[source,yaml]
====
engine:
  asciidoctor:
    images-dir: "docs/images"
    libraries:
      - "asciidoctor-diagram"
    attributes:
      plantumlconfig: "_plantuml-config.txt"
      coherence-maven-group-id: "${coherence.group.id}"
      version-coherence: "${revision}"
      version-commercial-docs: "14.1.1.0"
      version-helidon: "${helidon.version}"
====

The format of an attribute is name followed by a colon, and the attribute value in quotes,
so above the value of the `version-commercial-docs` attribute is `14.1.1.0`.

Attributes can be taken from Maven build properties by using the normal Maven property replacement string as the value.
For example the `version-coherence` attribute's value will be the Maven `revision` property value.

In the `.adoc` files the attributes are then substituted by putting the attribute name in curly brackets.

For example:
====
The current commercial Coherence version is {version-commercial-docs}.
====
would become
====
The current commercial Coherence version is 14.1.1.0.
====

