///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2024, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Introduction
:description: Oracle Coherence CE Documentation - Introduction
:keywords: coherence, java, documentation, introduction

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Introduction

First and foremost, Coherence provides a fundamental service that is responsible for all facets of clustering and is a
common denominator / building block for all other Coherence services.
This service, referred to as 'service 0' internally, ensures the mesh of members is maintained and responsive,
taking action to collaboratively evict, shun, or in some cases voluntarily depart the cluster when deemed necessary.
As members join and leave the cluster, other Coherence services are notified thus allowing those services to react accordingly.

NOTE: This part of the Coherence product has been in production for 20+ years, and has been the subject of some extensive and
imaginative testing.
While it has been discussed here it certainly is not something that customers, generally, interact with directly but is
valuable to be aware of.

Coherence services build on top of the clustering service, with the key implementations to be aware of being
PartitionedService, InvocationService, and ProxyService.

In the majority of cases customers will deal with caches;
a cache will be represented by an implementation of `NamedCache<K,V>`.
Cache is an unfortunate name, as many customers use Coherence as a system-of-record rather than a lossy store of data.
A cache is hosted by a service, generally the PartitionedService, and is the entry point to storing, retrieving,
aggregating, querying, and streaming data.

There are a number of features that caches provide:

* Fundamental *key-based access*: get/put getAll/putAll
* Client-side and storage-side events
 ** *MapListeners* to asynchronously notify clients of changes to data
 ** *EventInterceptors* (either sync or async) to be notified storage level events, including mutations, partition transfer, failover, etc
* *NearCaches* - locally cached data based on previous requests with local content invalidated upon changes in storage tier
* *ViewCaches* - locally stored view of remote data that can be a subset based on a predicate and is kept in sync real time
* *Queries* - distributed, parallel query evaluation to return matching key, values or entries with potential to optimize performance with indices
* *Aggregations* - a map/reduce style aggregation where data is aggregated in parallel on all storage nodes and results streamed back to the client for aggregation of those results to produce a final result
* *Data local processing* - an ability to send a function to the relevant storage node to execute processing logic for the appropriate entries with exclusive access
* *Partition local transactions* - an ability to perform scalable transactions by associating data (thus being on the same partition) and manipulating other entries on the same partition potentially across caches
* *Non-blocking / async NamedCache API*
* *Polyglot clients* - access the same NamedCache API from https://github.com/oracle/coherence-cpp-extend-client[C++], https://github.com/oracle/coherence-go-client[Go], Java, https://github.com/oracle/coherence-js-client[JavaScript], https://github.com/oracle/coherence-dotnet-extend-client[.NET], or https://github.com/oracle/coherence-py-client[Python]
* *Portable Object Format* - optimized serialization format, with the ability to navigate the serialized form for optimized queries, aggregations, or data processing
* *Integration with Databases* - Database & third party data integration with CacheStores including both synchronous or asynchronous writes
* *CohQL* - ansi-style query language with a console for adhoc queries
* *Topics* - distributed topics implementation offering pub/sub messaging with the storage capacity the cluster and parallelizable subscribers
* *Repository API* - a framework implementing the Repository pattern from Domain-Driven Design, abstracting persistent storage implementation from application code, with advanced features like support for pagination, projections, streaming, and updating in-place
* *coherence-concurrent* - Coherence-backed implementations of types from the `java.util.concurrent` package enabling distributed process coordination through the grid
** *Atomics* - for implementing e.g. atomic counters shared between cluster, with an optional asynchronous API
** *Executors* - for submitting tasks to be executed in the cluster
** *Locks* - for implementing lock-based concurrency control across multiple cluster members
** *Queues* - for implementing blocking queue / dequeue behavior across multiple cluster members
** *Semaphores* - for implementing synchronization of execution across multiple cluster members
* *Microservices integration* - broad and close integration with https://docs.oracle.com/en/middleware/fusion-middleware/coherence/14.1.2/integrate/coherence-microprofile-config.htm[Helidon], https://micronaut-projects.github.io/micronaut-coherence/latest/guide/[Micronaut], and https://spring.coherence.community/4.3.0/#/about/01_overview[Spring] for developing microservices applications using Coherence as a data source or cache

There are also a number of non-functional features that Coherence provides:

* *Rock solid clustering* - highly tuned and robust clustering stack that allows Coherence to scale to thousands of members in a cluster with thousands of partitions and terabytes of data being accessed, mutated, queried and aggregated concurrently
* *Safety first* - resilient data management that ensures backup copies are on distinct machines, racks, or sites and the ability to maintain multiple backups
* *24/7 Availability* - zero down time with rolling redeploy of cluster members to upgrade application or product versions
 ** Backwards and forwards compatibility of product upgrades, including major versions
* *Persistent Caches* - with the ability to use local file system persistence (thus avoid extra network hops) and leverage Coherence consensus protocols to perform distributed disk recovery when appropriate
* *Distributed State Snapshot* - ability to perform distributed point-in-time snapshot of cluster state, and recover snapshot in this or a different cluster (leverages persistence feature)
* *Lossy redundancy* - ability to reduce the redundancy guarantee by making backups and/or persistence asynchronous from a client perspective
* *Single Mangement View* - provides insight into the cluster  with a single JMX server that provides a view of all members of the cluster
* *Management over REST* - all JMX data and operations can be performed over REST, including cluster wide thread dumps and heapdumps
* *Non-cluster Access* - access to the cluster from the outside via proxies, for distant (high latency) clients and for non-Java languages such as https://github.com/oracle/coherence-cpp-extend-client[C++], https://github.com/oracle/coherence-go-client[Go], https://github.com/oracle/coherence-js-client[JavaScript], https://github.com/oracle/coherence-dotnet-extend-client[.NET], or https://github.com/oracle/coherence-py-client[Python]
* *Kubernetes friendly* - seamlessly and safely deploy applications to k8s with our own https://github.com/oracle/coherence-operator[operator]


== Coherence Community Edition Disabled and Excluded Functionality

Coherence Community Edition does not include the following Oracle Coherence commercial edition functionality

* Management of Coherence via the Oracle WebLogic Management Framework
* WebLogic Server Multi-tenancy support
* Deployment of Grid Archives (GARs)
* HTTP session management for application servers (Coherence*Web)
* GoldenGate HotCache
* TopLink-based CacheLoaders and CacheStores
* Elastic Data
* Federation and WAN (wide area network) support
* Transaction Framework
* CommonJ work manager
