///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2020, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Quick Start

=== Prerequisites

. Java - jdk8 or higher
. Maven - 3.6.3 or higher

=== Downloading Coherence Community Edition

As Coherence is generally embedded into an application by using Coherence APIs,
the natural place to consume this dependency is from Maven:

[source,xml]
.pom.xml
----
<dependencies>
    <dependency>
        <groupId>com.oracle.coherence.ce</groupId>
        <artifactId>coherence</artifactId>
        <version>20.06</version>
    </dependency>
</dependencies>
----

You can also get Coherence from the official https://hub.docker.com/r/oraclecoherence/coherence-ce[Docker image].
For other language clients, use     (http://github.com/oracle/coherence-cpp-extend-client[C{pp}] and
http://github.com/oracle/coherence-dotnet-extend-client[.NET]), and for the non-community edition, see https://www.oracle.com/middleware/technologies/coherence-downloads.html[Oracle Technology Network].

== CLI Hello Coherence

The following example illustrates the procedure to start a *storage enabled* Coherence Server, followed by a *storage disabled*
Coherence Console.
Using the console, data is
inserted, retrieved, and then the console is terminated. The console is restarted
and data is once again retrieved to illustrate the permanence of the data.

NOTE: This example uses the out-of-the-box cache configuration and therefore, explicitly specifying that the console is
storage disabled is unnecessary.

NOTE: Coherence cluster members discover each other via one of two mechanisms;
multicast (default) or Well Known Addressing (deterministic broadcast).
If your system does not support multicast, enable WKA by specifying `-Dcoherence.wka=localhost` for both processes
started in the following console examples.

=== +++<a name="cohql">++++++</a>+++CohQL Console

To run a CohQL console:

[source,shell]
----

$> mvn -DgroupId=com.oracle.coherence.ce -DartifactId=coherence -Dversion=20.06 dependency:get

$> export COH_JAR=~/.m2/repository/com/oracle/coherence/ce/coherence/20.06/coherence-20.06.jar

$> java -jar $COH_JAR &

$> java -cp $COH_JAR com.tangosol.coherence.dslquery.QueryPlus

CohQL> select * from welcomes

CohQL> insert into welcomes key 'english' value 'Hello'

CohQL> insert into welcomes key 'spanish' value 'Hola'

CohQL> insert into welcomes key 'french' value 'Bonjour'

CohQL> select key(), value() from welcomes
Results
["french", "Bonjour"]
["english", "Hello"]
["spanish", "Hola"]

CohQL> bye

$> java -cp $COH_JAR com.tangosol.coherence.dslquery.QueryPlus

CohQL> select key(), value() from welcomes
Results
["french", "Bonjour"]
["english", "Hello"]
["spanish", "Hola"]

CohQL> bye

$> kill %1
----

=== +++<a name="coh-console">++++++</a>+++Coherence Console

To run the Coherence console:

[source,shell]
----

$> mvn -DgroupId=com.oracle.coherence.ce -DartifactId=coherence -Dversion=20.06 dependency:get

$> export COH_JAR=~/.m2/repository/com/oracle/coherence/ce/coherence/20.06/coherence-20.06.jar

$> java -jar $COH_JAR &

$> java -cp $COH_JAR com.tangosol.net.CacheFactory

Map (?): cache welcomes

Map (welcomes): get english
null

Map (welcomes): put english Hello
null

Map (welcomes): put spanish Hola
null

Map (welcomes): put french Bonjour
null

Map (welcomes): get english
Hello

Map (welcomes): list
french = Bonjour
spanish = Hola
english = Hello

Map (welcomes): bye

$> java -cp $COH_JAR com.tangosol.net.CacheFactory

Map (?): cache welcomes

Map (welcomes): list
french = Bonjour
spanish = Hola
english = Hello

Map (welcomes): bye

$> kill %1
----

== +++<a name="hello-coh">++++++</a>+++Programmatic Hello Coherence Example

The following example illustrates starting a *storage enabled* Coherence server, followed by running the `HelloCoherence`
application.
The `HelloCoherence` application inserts and retrieves data from the Coherence server.

=== Build `HelloCoherence`

. Create a maven project either manually or by using an archetype such as maven-archetype-quickstart
. Add a dependency to the pom file:
[source,xml]
----
<dependency>
  <groupId>com.oracle.coherence.ce</groupId>
  <artifactId>coherence</artifactId>
  <version>20.06</version>
</dependency>
----

. Copy and paste the following source to a file named src/main/java/HelloCoherence.java:

[source,java]
.HelloCoherence.java
----
import com.tangosol.net.CacheFactory;
import com.tangosol.net.NamedMap;

public class HelloCoherence
    {
    // ----- static methods -------------------------------------------------

    public static void main(String[] asArgs)
        {
        NamedMap<String, String> map = CacheFactory.getCache("welcomes");

        System.out.printf("Accessing map \"%s\" containing %d entries\n",
                map.getName(),
                map.size());

        map.put("english", "Hello");
        map.put("spanish", "Hola");
        map.put("french" , "Bonjour");

        // list
        map.entrySet().forEach(System.out::println);
        }
    }
----

. Compile the maven project:
+
[source,shell]
----
mvn package
----

. Start a Storage server
+
[source,shell]
----
mvn exec:java -Dexec.mainClass="com.tangosol.net.DefaultCacheServer" &
----

. Run `HelloCoherence`
+
[source,shell]
----
mvn exec:java -Dexec.mainClass="HelloCoherence"
----

. Confirm that you see the output including the following:
+
[source,shell]
----
Accessing cache "welcomes" containing 3 entries
ConverterEntry{Key="french", Value="Bonjour"}
ConverterEntry{Key="spanish", Value="Hola"}
ConverterEntry{Key="english", Value="Hello"}
----

. Kill the storage server started earlier:
+
[source,shell]
----
kill %1
----

== +++<a name="build">++++++</a>+++Building

[source,shell]
----

$> git clone git@github.com:oracle/coherence.git
$> cd coherence/prj

# build all modules
$> mvn clean install

# build all modules skipping tests
$> mvn clean install -DskipTests

# build a specific module, including all dependent modules and run tests
$> mvn -am -pl test/functional/persistence clean verify

# build only coherence.jar without running tests
$> mvn -am -pl coherence clean install -DskipTests

# build only coherence.jar and skip compilation of CDBs and tests
$> mvn -am -pl coherence clean install -DskipTests -Dtde.compile.not.required
----
