///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2022, 2024 Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Important Changes in Coherence Community Edition (CE)

== Java Development Kit Requirements

Coherence CE {version-coherence} requires a minimum of version
17 of the Java Development Kit (JDK).

=== Concerning Java Platform Module (JPMS) Options

JPMS JDK command line options such as *--add-opens*, *--add-exports* and *--add-reads* of standard JDK modules to *com.oracle.coherence* module documented in Section *Using Java Modules to Build a Coherence Application* of Coherence commercial release 14.1.1.2206 are no longer required.

A new JPMS requirement is an application module containing Coherence remote lambda(s) must open itself to module *com.oracle.coherence* so the remote lambda(s) can be resolved to the application's lambda(s) during deserialization.

