/*
 * Copyright (c) 2026, Oracle and/or its affiliates.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at
 * https://oss.oracle.com/licenses/upl.
 */

plugins {
    id 'base'
}

tasks.named('build') {
    dependsOn subprojects.collect { "${it.path}:build" }
}

tasks.named('clean') {
    dependsOn subprojects.collect { "${it.path}:clean" }
}
