///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Configure Coherence Topics
:description: Coherence Topics
:keywords: coherence, topics, java, documentation

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Configure Coherence Topics

Coherence topics are configured in the cache configuration file.

This section includes the following topics:

* <<topic-mapping,Defining Topic Mappings>> - A topic mapping maps a topic name to a paged topic scheme definition.
** <<groups,Define Subscriber Groups>> - Subscriber groups can be defined in topic mappings
* <<scheme,Defining a Distributed Topic Scheme>> - Topic schemes are used to define the topic services that are available to an application.
** <<channel-count,Channel Count>> - configure the number of channels in a topic
** <<retain,Retaining Messages (Topics as Persistent Logs)>> - retain messages after consumption (rewindable topics)
** <<serializer,Configure the message Serializer>>
** <<subscriber-timeout,Configure the Subscriber Timeout>> - configure the group subscriber timout
** <<storeage,Storage Options for Topic Values>>
** <<page-size,Page Size>> - configure the size of a page in a paged topic
** <<size-limit,Size Limited Topics>>
** <<expiry,Expiring Messages>> - expiring messages



[#topic-mapping]
=== Defining Topic Mappings
A topic mapping maps a topic name to a paged topic scheme definition.The mappings provide a level of separation between applications and the underlying topic definitions. The separation allows topic implementations to be changed as required without having to change application code. Topic mappings have optional initialization parameters that are applied to the underlying paged topic scheme definition.
Topic mappings are defined using a `<topic-mapping>` element within the `<topic-scheme-mapping>` node. Any number of topic mappings can be created. The topic mapping must include the topic name, and the scheme name to which the topic name is mapped.

==== Using Exact Topic Mappings

An exact topic mapping maps a specific topic name to a topic scheme definition. An application must provide the exact name as specified in the mapping to use a topic. The slash (/) and colon (:) are reserved characters and cannot be used in topic names. The example below creates a single topic mapping that maps the topic name `exampleTopic` to a `paged-topic-scheme definition with the scheme name `example-topic-scheme`.

[source,xml]
.Sample Exact Topic Mapping
----
<?xml version="1.0"?>
<cache-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-cache-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-cache-config coherence-cache-config.xsd">
   <topic-scheme-mapping>
      <topic-mapping>
         <topic-name>exampleTopic</topic-name>
         <scheme-name>topic-scheme</scheme-name>
      </topic-mapping>
   </topic-scheme-mapping>
   <caching-schemes>
      <paged-topic-scheme>
         <scheme-name>example-topic-scheme</scheme-name>
         <service-name>DistributedTopicService</service-name>
      </paged-topic-scheme>
   </caching-schemes>
</cache-config>
----

==== Using Named Pattern Topic Mappings

Name pattern topic mappings allow applications to use patterns when specifying a topic name. Patterns use the asterisk (`\*`) wildcard. Name patterns alleviate an application from having to know the exact name of a topic. The slash (/) and colon (:) are reserved characters and cannot be used in topic names. The example below a topic mappings using the wildcard (`\*`) to map any topic name with the prefix `account-` to a `paged-topic-scheme` definition with the scheme name `account-topic-scheme`.

[source,xml]
.Sample Topic Name Pattern Mapping
----
<?xml version="1.0"?>
<cache-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-cache-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-cache-config coherence-cache-config.xsd">
    <topic-scheme-mapping>
      <topic-mapping>
          <topic-name>account-*</topic-name>
          <scheme-name>account-topic-scheme</scheme-name>
      </topic-mapping>
    </topic-scheme-mapping>

    <caching-schemes>
      <paged-topic-scheme>
          <scheme-name>account-topic-scheme</scheme-name>
          <service-name>AccountDistributedTopicService</service-name>
      </paged-topic-scheme>
    </caching-schemes>
</cache-config>
----

[#groups]
==== Subscriber Group

A topic can have zero, one, or more durable subscriber groups defined in the topic-mapping for the topic. The subscriber group(s) are created along with the topic and are therefore ensured to exist before any data is published to the topic.

NOTE: A subscriber group does not have to be defined on a topic’s topic-mapping for a subscriber to be able to join its group. Groups can be created and destroyed dynamically at runtime in application code.

The example below adds the subscriber group `durableSubscription` to the `exampleTopic` mapping.
The `subscriber-groups` element can contain multiple `subscriber-group` elements to add as many groups as the application requires.

[source,xml]
.Sample Durable Subscriber Group
----
<?xml version="1.0"?>
<cache-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-cache-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-cache-config coherence-cache-config.xsd">

   <topic-scheme-mapping>
      <topic-mapping>
         <topic-name>exampleTopic</topic-name>
         <scheme-name>topic-scheme</scheme-name>
         <subscriber-groups>
             <subscriber-group>
                 <name>durableSubscription</name>
             </subscriber-group>
         <subscriber-groups>
      </topic-mapping>
   </topic-scheme-mapping>

   <caching-schemes>
      <paged-topic-scheme>
         <scheme-name>topic-scheme</scheme-name>
         <service-name>DistributedTopicService</service-name>
      </paged-topic-scheme>
   </caching-schemes>
</cache-config>
----

[#scheme]
=== Defining a Distributed Topic Scheme
Topic schemes are used to define the topic services that are available to an application.Topic schemes provide a declarative mechanism that allows topics to be defined independent of the applications that use them. This removes the responsibility of defining topics from the application and allows topics to change without having to change an application's code. Topic schemes also promote topic definition reuse by allowing many applications to use the same topic definition.
Topic schemes are defined within the <caching-schemes> element. A <paged-topic-scheme> scheme element and its properties are used to define a topic of that type.

==== Sample Distributed Topic Definition

The `<paged-topic-scheme>` element is used to define distributed topics. A distributed topic utilizes a distributed (partitioned) topic service instance. Any number of distributed topics can be defined in a cache configuration file.

The example below defines a basic distributed topic that uses `distributed-topic` as the scheme name and is mapped to the topic name `example-topic`. The `<autostart>` element is set to `true` to start the service on a cache server node.

[source,xml]
.coherence-cache-config.xml
----
<?xml version="1.0"?>
<cache-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-cache-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-cache-config coherence-cache-config.xsd">

   <topic-scheme-mapping>
     <topic-mapping>
       <topic-name>example-topic</topic-name>
       <scheme-name>distributed-topic</scheme-name>
     </topic-mapping>
   </topic-scheme-mapping>

   <caching-schemes>
     <paged-topic-scheme>
        <scheme-name>distributed-topic</scheme-name>
        <service-name>DistributedTopicService</service-name>
        <autostart>true</autostart>
     </paged-topic-scheme>
   </caching-schemes>
</cache-config>
----

A `paged-topic-scheme` has various configuration elements, discussed further below.

[#channel-count]
==== Channel Count

Channels are used by topics both as a way to increase parallel processing of messages and also to retain published ordering. The number of channels in a topic is configurable using the `<channel-count>` sub-element of the `<paged-topic-scheme>`.

The default number of channels is based on the partition count of the underlying cache service used by the topic. With the Coherence default partition count of 257 giving a default topic channel count of 17.

[source,xml]
.coherence-cache-config.xml
----
 <paged-topic-scheme>
    <scheme-name>distributed-topic</scheme-name>
    <service-name>DistributedTopicService</service-name>
    <autostart>true</autostart>
    <channel-count>3</channel-count> <1>
 </paged-topic-scheme>
----
<1> The example above configures the topics mapped to the `distributed-topic` scheme to have a channel count of `3`.

Whether increasing or decreasing the channel count makes sense depends on how an application will publish messages, and the ordering guarantees required. To help show the pros and cons we'll look at both the very small and the very big.

===== Very Small Channel Count

The smallest channel count possible would be one. With one channel all messages published will go to this single channel. The channel will have a single tail location where messages are published to and subscribed from.

If there is only a single publisher that requires ordering of all messages it publishes then a single channel would work. If there are multiple publishers then with a single channel all publishers will publish to this one channel and there will be contention on the tail of the topic if the publishers all try to publish at the same time. If the multiple publishers require global ordering of messages across publishers then one channel will give this at the cost of performance due to contention. If the publishers are not publishing very often, the contention would be reduced.

Multiple anonymous subscribers can all subscribe to a single channel and receive messages in order.

Using a subscriber group on a single channel topic does not allow multiple subscribers in the group to scale out message processing. IN a subscriber group, subscribers own channels that they subscribe to, so with only a single channel, only one subscriber in the group can receive messages.

===== Vary Large Channel Count

Setting a very large channel count (100s or 1000s) whilst possible would be impractical. One reason is that various data structures used by topics are created per-channel (or per-partition per-channel) so having a very large number of channels will use more resources, such as heap, to maintain these structures.

A larger number of channels would have less contention where many publishers are publishing messages at the same time.

A larger number of channels would allow more subscribers in a group to process messages in parallel, assuming that either there are enough publishers publishing to all of those channels, or the publishers are configured to publish to multiple channels.

In most cases the default channel count should be about right. Applications may wish to slightly reduce or increase this and there are use-cases where one channel may be suitable. An excessively large number of channels is probably not justifiable.

[#retain]
==== Retaining Messages (Topics as Persistent Logs)

By default, messages in a topic are removed after all the currently connected anonymous subscribers and all the subscriber groups have processed and committed a message. This means a message can only be read once. When an anonymous subscriber connects to a topic it starts receiving messages with the next message published to the topic after it connects. The subscribers in a new subscriber group will also receive messages that were published after the group was created.

Sometimes it is desirable to have a topic behave more like a persistent log structure, where a subscriber, or subscriber group, in an application can receive the ordered messages from the log, then go back and re-read them as required. The `<retain-consumed>` sub-element of the `<paged-topic-scheme>` element controls this behaviour. The `<retain-consumed>` sub-element's value is a boolean, `true` to retain elements, `false` to remove consumed elements.

In topics configured with `<retain-consumed>` set to `true`, new anonymous subscribers will start to receive messages from the beginning (head) of the topic, rather than the tail; new subscriber groups will also start from the head of the topic.

Messages in a retained topic are never deleted (unless the topic is also configured with expiry).

[source,xml]
.coherence-cache-config.xml
----
 <paged-topic-scheme>
    <scheme-name>distributed-topic</scheme-name>
    <service-name>DistributedTopicService</service-name>
    <autostart>true</autostart>
    <retain-consumed>true</retain-consumed> <1>
 </paged-topic-scheme>
----
<1> The example above configures the topics mapped to the `distributed-topic` scheme to retain messages.

Topics configuration, like cache configuration, supports parameterizing certain configuration elements on a per-topic basis using parameter macros.

For example, the configuration below has tow topic mappings, `topic-one` and `topic-two`.

[source,xml]
.coherence-cache-config.xml
----
<?xml version="1.0"?>
<cache-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-cache-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-cache-config coherence-cache-config.xsd">

   <topic-scheme-mapping>
    <topic-mapping>
      <topic-name>topic-one</topic-name>
      <scheme-name>distributed-topic</scheme-name>
      <init-params>
        <init-param>
          <param-name>keep-messages</param-name>        <1>
          <param-value>true</param-value>
        </init-param>
      </init-params>
    </topic-mapping>

    <topic-mapping>
      <topic-name>topic-two</topic-name>                <2>
      <scheme-name>distributed-topic</scheme-name>
    </topic-mapping>

   </topic-scheme-mapping>

   <caching-schemes>
     <paged-topic-scheme>
        <scheme-name>distributed-topic</scheme-name>
        <service-name>DistributedTopicService</service-name>
        <autostart>true</autostart>
        <retain-values>{keep-messages false}</retain-values>  <3>
     </paged-topic-scheme>
   </caching-schemes>
</cache-config>
----

<1> The `topic-one` mapping contains an `init-param` named `keep-messages` with a value of `true`
<2> The `topic-two` mapping contains no `init-params`
<3> The topic scheme contains the `retain-values` sub-element, but instead of a simple boolean value it uses a macro (a value inside curly brackets). The `{keep-messages false}` macro says to use the `keep-messages` parameter for the value of the `retain-values` sub-element, and default to `false` if `keep-messages` is not set.

So, `topic-one`, which sets `keep-values` to `true` will use a configuration that retains messages, whereas `topic-two` has no `init-params` so `keep-values` will not be set and will default to `false.


[#serializer]
==== Topic Values Serializer

The `<serializer>` sub-element of `<paged-topic-scheme>` element enables specifying predefined serializers `pof` or `java` (default), or a custom `Serializer` implementation. The serializer is used to serialize and deserialize the message payload.

[source,xml]
.coherence-cache-config.xml
----
 <paged-topic-scheme>
    <scheme-name>topic-scheme</scheme-name>
    <service-name>TopicService</service-name>
    <serializer>pof</serializer>   <1>
    <autostart>true</autostart>
 </paged-topic-scheme>
----
<1> the example above sets the serializer for all topics mapped to the `distributed-topic` scheme to POF.


[#subscriber-timeout]
==== Subscriber Timeout

The `subscriber-timeout` sub-element configures the maximum amount of time that can elapse after a subscribers that is part of a subscriber group polls for messages before that subscriber is considered dead. Each time a subscriber in a group calls on of the `receive` methods it sends a heartbeat to the server (heartbeats can also be sent manually by application code during long-running processing). If the server does not receive a heartbeat within the timeout the subscriber is considered dead and any channels that it owned will be redistributed to any remaining subscribers.

[source,xml]
.coherence-cache-config.xml
----
 <paged-topic-scheme>
    <scheme-name>topic-scheme</scheme-name>
    <service-name>TopicService</service-name>
    <autostart>true</autostart>
    <subscriber-timeout>1m</subscriber-timeout>  <1>
 </paged-topic-scheme>
----
<1> The subscriber timeout has been set to 1 minute.

The purpose of timing out subscribers is to stop channels being starved of subscriptions due to badly behaved, dead, or deadlocked subscribers. If a dead subscriber stayed connected and its channels were not redistributed, any messages published to those channels would never be processed.

A timed-out subscriber is not closed, application code that calls receive on a timed-ot subscriber will cause that subscriber to reconnect and be re-initialised with new channel ownership.

The default value for the subscriber timeout is five minutes. This should be sufficient for most applications unless the message processing code takes a very long time, for example it talks to other external slow system.

[#storeage]
==== Storage Options for Topic Values

The `<storage>` sub-element allows specification of `on-heap`, `ramjournal` and `flashjournal` to store the messages and metadata for a topic. The default is to use on-heap storage. The `ramjournal` and `flashjournal` options use the Elastic Data Feature to, which is a commercial only Coherence feature.

[source,xml]
.coherence-cache-config.xml
----
 <paged-topic-scheme>
    <scheme-name>topic-scheme</scheme-name>
    <service-name>TopicService</service-name>
    <storage>on-heap</storage>   <1>
    <autostart>true</autostart>
 </paged-topic-scheme>
----
<1> the example above sets storage to `on-heap`, so topic data is stored in memory.


[source,xml]
.coherence-cache-config.xml
----
 <paged-topic-scheme>
    <scheme-name>topic-scheme</scheme-name>
    <service-name>TopicService</service-name>
    <storage>flashjournal</storage>   <1>
    <autostart>true</autostart>
 </paged-topic-scheme>
----
<1> the example above sets storage to `flashjournal`, so topic data is stored on disc, using Coherence's commercial Elastic Data feature.


[#page-size]
==== Page Size

A paged topic scheme configures a topic that stores data in pages. This is how Coherence scales topic data across the cluster, by distributing pages across storage enabled members of the cluster. Each channel has pages and each page holds a number of messages. The page size can be configured to determine how many messages can fit into a page. Publishers publish messages to the tail page in a channel, and when that page is full the page is sealed, and the next page becomes the tail.

Page size is configured in the `<page-size>` element of the `<paged-topic-scheme>` in the cache configuration file.
The format of the page size value is a positive integer, optionally followed by a byte size suffix (B, KB, MB).

When the page size is configured with a value using a byte size suffix, the size of the serialized message payload is used to determine the page size. In this case different pages may contain different numbers of messages if the serialized message size is different.

In the example below, the page size is set to 10 mega-bytes:
[source,xml]
.coherence-cache-config.xml
----
<paged-topic-scheme>
    <scheme-name>topic-scheme</scheme-name>
    <service-name>TopicService</service-name>
    <autostart>true</autostart>
    <page-size>10MB</page-size>
</paged-topic-scheme>
----

If a page size element has a value without a byte size suffix it is treated as a number of messages rather than a binary size. For example, using the configuration below, each page will have a maximum size of 100 messages, regardless of the message's size in bytes:

[source,xml]
.coherence-cache-config.xml
----
<paged-topic-scheme>
    <scheme-name>topic-scheme</scheme-name>
    <service-name>TopicService</service-name>
    <autostart>true</autostart>
    <page-size>100</page-size>
</paged-topic-scheme>
----

Pages are used by subscribers as a way to batch receive calls. When receive is called on a subscriber, the server can return a batch of messages, upto a whole page, in the response. The subscriber then stores those messages locally and uses them to respond to further receive calls without needing to make a remote request back to the page. The default maximum batch size used in responses is the minimum of the page size, and the MTU of the network interface being used by Coherence, so that a batch fits into a network packet.

As with many configuration elements, there are pros and cons to making the value too small or too large.
A page that is too large will store a lot of data in a single page on a single storage member before moving to the next page, causing lumpy data distribution. Pages that are too small will cause an excessive number of pages wasting storage where the data structures created per page may exceed the storage used by the messages themselves.

The default page size is 1Mb. Page numbers are stored in a Java long value, so an application is unlikely to consume all 9,223,372,036,854,775,807 pages. Using the default page size of 1Mb, that is 9 peta-bytes of messages.

Due to the way publishing works, a full page usually slightly exceeds the configured page size. This is because during publishing, messages are accepted into a page until the pages size is >= the configured maximum. For example, if a page has been configured with a maximum size of 1Mb and currently has 900kb of messages, so is below the maximum size. If the next message published that is 150kb, that message will still be accepted, as the page has some free space, pushing the total size to 1.5Mb. The page would then be considered sealed and accept no more messages, the next message published would go to the next page.

[#size-limit]
==== Size Limited Topics

Adding a `<high-units>` sub-element to `<paged-topic-scheme>` element limits the storage size of the values retained for the topic. The topic is considered full if this storage limit is reached. Not exceeding this high water-mark is managed by using flow control. When subscriber(s) are lagging in processing outstanding values retained on the topic, the publishers are throttled until there is space available. See Managing the Publisher Flow Control to Place Upper Bound on Topics Storage.

[source,xml]
.coherence-cache-config.xml
----
<paged-topic-scheme>
    <scheme-name>topic-scheme</scheme-name>
    <service-name>TopicService</service-name>
    <autostart>true</autostart>
    <high-units>100MB</high-units>  <1>
</paged-topic-scheme>
----
<1> The `<high-units>` has been set to 100Mb so the total size of the topic will not exceed 100 mega-bytes.


[#expiry]
==== Topics with Expiring Values

Adding a `<expiry-delay>` sub-element to `<paged-topic-scheme>` element limits the length of time that the published messages live in a topic, waiting to be received by a Subscriber. Once the expiry delay is past, those expired messages will never be received by subscribers. The default `expiry-delay` is zero, meaning elements never expire.

Messages will be expired regardless of the type of subscriber used. For example, even with a durable subscriber group, expired messaged will not be received after their expiry delay has passed.

[source,xml]
.coherence-cache-config.xml
----
<paged-topic-scheme>
    <scheme-name>topic-scheme</scheme-name>
    <service-name>TopicService</service-name>
    <autostart>true</autostart>
    <expiry-delay>30d</expiry-delay>  <1>
</paged-topic-scheme>
----
<1> The `<expiry-delay>` has been set to 30 days, so messages will be removed from the topic 30 days after publishing, regardless of whether they have been received by subscribers.