///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Monitoring StatusHA
:description: Coherence Guides Monitoring StatusHA
:keywords: coherence, java, documentation, Monitoring StatusHA

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Monitoring StatusHA

This guide walks you through how to monitor the High Available (HA) Status or `StatusHA`
value for Coherence Partitioned Services within a cluster.

`StatusHA` is most commonly used to ensure services are in a
safe state between restarting cache servers during a rolling restart.

See the Coherence documentation on
{commercial-docs-base-url}/develop-applications/starting-and-stopping-cluster-members.html[Starting and Stopping Cluster Members]
for more information on rolling redeploys.

=== Table of Contents

* <<what-you-will-build,What You Will Build>>
* <<what-you-will-need,What You Need>>
* <<building, Building the Example Code>>
* <<example-classes-1, Review the Classes>>
* <<run-example-1, Run the Example>>
** <<run-example-usage, Show Usage>>
** <<run-example-start-cache-servers, Start 4 cache servers>>
** <<run-example-start, Start example>>
** <<run-example-kill, Kill a cache server>>
** <<run-example-kill-more, Kill more cache servers>>
** <<run-example-other, Experiment with other connection options>>
** <<run-example-package, Packaging the example>>
* <<summary, Summary>>
* <<see-also, See Also>>

[#what-you-will-build]
=== What You Will Build

In this example you will build and run a utility allowing you to monitor `StatusHA` values for Coherence services.

At its core, this example uses the `ServiceMBean` as described
in the {commercial-docs-base-url}/manage/oracle-coherence-mbeans-reference.html[Coherence documentation].
In particular the following attributes are queried:

* StatusHA - The High Availability (HA) status for this service. A value of MACHINE-SAFE indicates that all the cluster members running on any given computer could be stopped without data loss. A value of NODE-SAFE indicates that a cluster member could be stopped without data loss. A value of ENDANGERED indicates that abnormal termination of any cluster member that runs this service may cause data loss. A value of N/A indicates that the service has no high availability impact.
* StorageEnabledCount - Specifies the total number of cluster members running this service for which local storage is enabled
* PartitionsUnbalanced - The total number of primary and backup partitions that remain to be transferred until the partition distribution across the storage enabled service members is fully balanced
* PartitionsVulnerable - The total number of partitions that are backed up on the same machine where the primary partition owner resides
* PartitionsEndangered - The total number of partitions that are not currently backed up
* PartitionsAll - The total number of partitions that every cache storage is divided into

The utility can connect to a Coherence cluster and query the MBeans using the following methods:

* Use MBeanServer from a cluster. Requires correct cluster config to join cluster. (Default)
* Use JMX URL to connect to a cluster
* Use a host and port to connect to a remote JMX process
* Use Management over REST to connect to a cluster via HTTP

*Continue on to review the example code or go directly <<run-example-1, here>> to run the example.*

[#what-you-will-need]
==== What You Need
:java_version: 1.8
:duration: 20
include::../../internal/includes/what-you-need.adoc[tag=text]

[#building]
==== Building the Example Code
include::../../internal/includes/simple-build.adoc[tag=text]

NOTE: This example can be built via Maven only. It is not supported to be run via Gradle.

NOTE: You can include the `-DskipTests` for Maven or `-x test` for Gradle, to skip the tests for now.

[#example-classes-1]
=== Review the Classes

The example consists of the following main classes:

** `StatusHAWatcher` - Main entrypoint to parse arguments and run the example
** `ServiceData` - Data structure to hold the service information queried from the cluster
** `DataFetcher` - Interface implemented by various classes to retrieve `ServiceMBean` details
** `MBeanServerProxyDataFetcher` - Implementation to retrieve data from `MBeanServerProxy`
** `JMXDataFetcher` - Implementation to retrieve data from a remote or local JMX connection
** `HTTPDataFetcher` - Implementation to retrieve data from a Management over REST connection from either standalone cluster or WebLogic Server

1. Review the `ServiceData` class
+
This class contains the following fields:
+
[source,java,indent=0]
----
include::src/main/java/com/oracle/coherence/guides/statusha/model/ServiceData.java[tag=attributes]
----

2. Review the `DataFetcher` interface
+
This interface defines the following methods which are used to retrieve `ServiceMBean` attributes via different methods
+
[source,java,indent=0]
----
include::src/main/java/com/oracle/coherence/guides/statusha/fetcher/DataFetcher.java[tag=class]
----

3. Review the `MBeanServerProxyDataFetcher` class
+
This class is an implementation of the `DataFetcher` interface to retrieve data from `MBeanServerProxy`.  
+
*Constructor*
+
[source,java,indent=0]
----
include::src/main/java/com/oracle/coherence/guides/statusha/fetcher/MBeanServerProxyDataFetcher.java[tag=constructor]
----
<1> Join the cluster and retrieve `Management`. The correct cluster operational override must be supplied to connect to the cluster.
<2> Retrieve the `MBeanServerProxy` instance
+
*getStatusHaData method*
+
[source,java,indent=0]
----
include::src/main/java/com/oracle/coherence/guides/statusha/fetcher/MBeanServerProxyDataFetcher.java[tag=getStatusHaData]
----
<1> Call `getMBeans()` to query the distribution coordinator MBean to retrieve all partitioned services
<2> Use `MBeanServerProxy` to get any `ServiceMBean` for the given service
<3> Retrieve all attributes from the `ServiceMBean`
<4> Add a new `ServiceData` instance to the set to return

4. Review the `JMXDataFetcher` class
+
This class is an implementation of the `DataFetcher` interface to retrieve data from a JMX connection.
+
*Constructor*
+
[source,java,indent=0]
----
include::src/main/java/com/oracle/coherence/guides/statusha/fetcher/JMXDataFetcher.java[tag=constructor]
----
<1> Retrieve an `JMXConnector` from the given JMX URL
<2> Retrieve an `MBeanServerConnection` from the `JMXConnector`
+
*getStatusHaData method*
+
[source,java,indent=0]
----
include::src/main/java/com/oracle/coherence/guides/statusha/fetcher/JMXDataFetcher.java[tag=getStatusHaData]
----
<1> Query the `MBeanServerConnection` to get any `ServiceMBean` for the given service
<2> Retrieve all required attributes

5. Review the `HTTPDataFetcher` class
+
This class is an implementation of the `DataFetcher` interface to retrieve data from a Management over REST connection.
+
*Constructor*
+
[source,java,indent=0]
----
include::src/main/java/com/oracle/coherence/guides/statusha/fetcher/HTTPDataFetcher.java[tag=constructor]
----
<1> If the URL is for a WebLogic Server connection, prompt for username/ password
+
*getMBeans method*
+
This method constructs a HTTP Request to retrieve the data from Management over REST endpoint.
+
[source,java,indent=0]
----
include::src/main/java/com/oracle/coherence/guides/statusha/fetcher/HTTPDataFetcher.java[tag=getMBeans]
----

[#run-example-1]
=== Run the Example

[#run-example-usage]
==== Show Usage

The supported way to run this example is to build using Maven as described <<building, here>> and running using
`java -jar target/status-ha-{version}.jar`
from a terminal in the base directory of this example: `examples/guides/500-status-ha`.

Firstly, issue the command with the `-u` option which displays the usage.

[source,bash,indent=0]
----
java -jar target/status-ha-{version}.jar -h

Usage: StatusHAWatcher [options]

Connection options:
 -m               Use MBeanServer from cluster. Requires correct cluster config to join cluster. (Default)
 -h url           Use Management over REST to connect to cluster
 -j url           Use JMX URL to connect to cluster
 -hp host:port    Connect to a JMX process via host:port

Other Options:
 -d delay         Delay between each check in seconds
 -s service       Service name to monitor or all services if not specified
 -u               Display usage

StatusHA meanings:
  ENDANGERED - abnormal termination of any cluster node that runs this service may cause data loss
  NODE-SAFE - any single cluster node could be stopped without data loss
  MACHINE-SAFE - all the cluster nodes running on any given machine could be stopped at once without data loss
  RACK-SAFE - all the cluster nodes running on any given rack could be stopped at once without data loss
  SITE-SAFE - all the cluster nodes running on any given rack could be stopped at once without data loss

Partition meanings:
  Endangered  - The total number of partitions that are not currently backed up
  Vulnerable  - The total number of partitions that are backed up on the same machine
                where the primary partition owner resides
  Unbalanced  - The total number of primary and backup partitions which remain to be transferred until the
                partition distribution across the storage enabled service members is fully balanced
  Remaining   - The number of partition transfers that remain to be completed before the service
                achieves the goals set by this strategy
----

NOTE: To test the utility we will start some cache servers.

[#run-example-start-cache-servers]
==== Start 4 cache servers

NOTE: If you want to connect using the default option, MBeanServer connection, you must ensure you build the example with the
same Coherence version of the cluster you are going to connect to.

1. Change to the ``examples/guides/500-status-ha/target/libs` directory

2. Issue the following command in four terminals to start 4 DefaultCacheServer processes.
+
NOTE: On two of the processes use `-Dcoherence.machine=machine1` and on the other two use `-Dcoherence.machine=machine2`
to simulate processes running on separate physical servers.
+
[source,bash,indent=0]
----
java -Dcoherence.machine=machine1 -jar coherence-{version}.jar
----

[#run-example-start]
==== Start the example

When the cache servers have started, ensure you are in the `examples/guides/500-status-ha` directory and run the following:

[source,bash,indent=0]
----
java -jar target/status-ha-{version}.jar
----

Notes:

1. By default, the MBeans will be queried every 5 seconds. You can change this by using the `-d` option and specify a delay in seconds.

2. All services are queried. You can select only a single service to be monitored by using `-s` option and specifying a service name.

You will see output similar to the following showing the status HA values for the cluster services.

[source,bash,indent=0]
----
Connection:   Cluster MBean Server
Service:      all
Delay:        5 seconds

Oracle Coherence Version 21.06.1
 Grid Edition: Development mode
Copyright (c) 2000, 2021, Oracle and/or its affiliates. All rights reserved.


Cluster Name: timmiddleton's cluster (21.06.1)

Press CTRL-C to quit

Date/Time                        Service Name         Storage Count  StatusHA         Partitions  Endangered  Vulnerable  Unbalanced  Status
----------------------------     ------------        --------------  ------------    ----------- ----------- ----------- -----------  -------------
Tue Aug 03 11:27:13 AWST 2021    PartitionedTopic                 4  MACHINE-SAFE            257           0           0           0  Safe
Tue Aug 03 11:27:13 AWST 2021    PartitionedCache                 4  MACHINE-SAFE            257           0           0           0  Safe

Tue Aug 03 11:27:18 AWST 2021    PartitionedTopic                 4  MACHINE-SAFE            257           0           0           0  Safe
Tue Aug 03 11:27:18 AWST 2021    PartitionedCache                 4  MACHINE-SAFE            257           0           0           0  Safe

Tue Aug 03 11:27:23 AWST 2021    PartitionedCache                 4  MACHINE-SAFE            257           0           0           0  Safe
Tue Aug 03 11:27:23 AWST 2021    PartitionedTopic                 4  MACHINE-SAFE            257           0           0           0  Safe
----

NOTE: You will notice that the StatusHA of all services is MACHINE-SAFE as there are an even number of cache
servers on each "machine".

[#run-example-kill]
==== Kill a cache server 

Kill one of the cache server processes using `CTRL-C` and note the change in the output of the example:

[source,bash,indent=0]
----
Date/Time                        Service Name         Storage Count  StatusHA         Partitions  Endangered  Vulnerable  Unbalanced  Status
----------------------------     ------------        --------------  ------------    ----------- ----------- ----------- -----------  -------------
Tue Aug 03 11:29:39 AWST 2021    PartitionedCache                 3  NODE-SAFE               257           0         257         170  170 partitions are unbalanced
Tue Aug 03 11:29:39 AWST 2021    PartitionedTopic                 3  NODE-SAFE               257           0          86           0  86 partitions are vulnerable

Tue Aug 03 11:29:45 AWST 2021    PartitionedCache                 3  NODE-SAFE               257           0          86           0  86 partitions are vulnerable
Tue Aug 03 11:29:45 AWST 2021    PartitionedTopic                 3  NODE-SAFE               257           0          86           0  86 partitions are vulnerable

Tue Aug 03 11:29:50 AWST 2021    PartitionedTopic                 3  NODE-SAFE               257           0          86           0  86 partitions are vulnerable
Tue Aug 03 11:29:50 AWST 2021    PartitionedCache                 3  NODE-SAFE               257           0          86           0  86 partitions are vulnerable
----

NOTE: You will notice that the StatusHA values are now node safe as there are not enough servers on each machine to
provide a higher level of safety.

[#run-example-kill-more]
==== Kill more cache servers

Kill all but one cache server, and you will notice the StatusHA value is ENDANGERED as there is only one cache server
with no backups available on other cache servers.

[source,bash,indent=0]
----

Date/Time                        Service Name         Storage Count  StatusHA         Partitions  Endangered  Vulnerable  Unbalanced  Status
----------------------------     ------------        --------------  ------------    ----------- ----------- ----------- -----------  -------------
Tue Aug 03 11:33:14 AWST 2021    PartitionedTopic                 1  ENDANGERED              257         257         257           0  StatusHA is ENDANGERED
Tue Aug 03 11:33:14 AWST 2021    PartitionedCache                 1  ENDANGERED              257         257         257           0  StatusHA is ENDANGERED

Tue Aug 03 11:33:19 AWST 2021    PartitionedCache                 1  ENDANGERED              257         257         257           0  StatusHA is ENDANGERED
Tue Aug 03 11:33:19 AWST 2021    PartitionedTopic                 1  ENDANGERED              257         257         257           0  StatusHA is ENDANGERED

Tue Aug 03 11:33:24 AWST 2021    PartitionedTopic                 1  ENDANGERED              257         257         257           0  StatusHA is ENDANGERED
Tue Aug 03 11:33:24 AWST 2021    PartitionedCache                 1  ENDANGERED              257         257         257           0  StatusHA is ENDANGERED
----

Start the remaining cache servers, and you will see the StatusHA return to MACHINE-SAFE.

[#run-example-other]
==== Experiment with other connection options

Other connection options are available which do not require you to have the same Coherence version as the example.

1. Connect via JMX to a Host/Port
+
If you have a Coherence MBean server running on a host/port you can connect to the cluster using the following:
+
[source,bash,indent=0]
----
java -jar target/status-ha-{version}.jar -hp host:port
----

2. Connect via JMX to a JMX URL
+
[source,bash,indent=0]
----
java -jar target/status-ha-{version}.jar -j service:jmx:rmi:///jndi/rmi://localhost:8888/jmxrmi
----

3. Connect via Management over REST
+
If you have a stand-alone Coherence cluster with Management over REST enabled, use the following:
+
[source,bash,indent=0]
----
java -jar target/status-ha-{version}.jar -h http://host:management-port/management/coherence/cluster
----

4. Connect via Management over REST to WebLogic Server
+
If you have a stand-alone Coherence cluster within WebLogic Server, use the following:
+
[source,bash,indent=0]
----
java -jar target/status-ha-{version}.jar -h http://host:admin-port/management/coherence/latest/clusters
----

[#run-example-package]
==== Packaging the example

When the example is built, the following artifacts are created:

* `target/status-ha-{version}.jar` - executable jar with META-INF/MANIFEST.MF adding `libs` directory contents to classpath
* `target/libs/coherence-{version}.jar` - Coherence version the example was built with
* `target/libs/jackson-annotations-2.12.0.jar` - required dependencies
* `target/libs/jackson-core-2.12.0.jar` - required dependencies
* `target/libs/jackson-databind-2.12.0.jar` - required dependencies

If you wish to take the example and run it on a separate machine, create a temporary directory and carry out the following:

NOTE: We are using a temporary directory `/tmp/build` as our example. Modify as you need.

[source,bash,indent=0]
----
cp target/status-ha-{version}.jar /tmp/build
mkdir /tmp/build/libs
cp target/libs/jackson-annotations-2.12.0.jar /tmp/build/libs
cp target/libs/jackson-core-2.12.0.jar /tmp/build/libs
cp target/libs/jackson-databind-2.12.0.jar /tmp/build/libs
----

You can then change to the `/tmp/build` directory and run the example using:

[source,bash,indent=0]
----
cd /tmp/build

java -jar status-ha-{version}.jar
----

Zip or Tar the directory up and transfer to your target machine.

If you wish to change the Coherence version used to build the example you can set the following system properties:

* `-Dcoherence.version` - the coherence version
* `-Dcoherence.group.id` - defaults to `com.oracle.coherence.ce`. Change to `com.oracle.coherence` for commercial edition.

[source,bash,indent=0]
----
mvn clean install -DskipTests -Dcoherence.version=14.1.1-0-0 -Dcoherence.groupid=com.oracle.coherence
----


[#summary]
=== Summary

In this example you built and ran a utility allowing you to monitor `StatusHA` values for Coherence services.

[#see-also]
=== See Also

* {commercial-docs-base-url}/manage/oracle-coherence-mbeans-reference.html[Coherence MBean Reference]
* {commercial-docs-base-url}/develop-applications/starting-and-stopping-cluster-members.html[Starting and Stopping Cluster Members]
* {commercial-docs-base-url}/manage/using-jmx-manage-oracle-coherence.html[Using JMX to Manage Oracle Coherence]
