///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2020, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Coherence gRPC Server

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Coherence gRPC Server

Coherence gRPC proxy is the server-side implementation of the services defined within the `Coherence gRPC` module.
The gRPC proxy uses standard gRPC Java libraries to provide Coherence APIs over gRPC.

== Usage

In order to use Coherence gRPC Server, you need to declare it as a dependency of your project;
for example if using Maven:

[source,xml]
----
<dependency>
  <groupId>com.oracle.coherence.ce</groupId>
  <artifactId>coherence-grpc-proxy</artifactId>
  <version>${coherence.version}</version>
</dependency>
----

or for Gradle:
[source,groovy]
----
implementation 'io.grpc:grpc-netty-shaded:1.32.1'
----

=== Start the Server

The gRPC server will start automatically when `com.tangosol.coherence.net.DefaultCacheServer` is started. Typically,
`DefaultCacheServer` will be used as the application's main class, alternatively an instance of `DefaultCacheServer`
can be started by calling its `main()` method directly from application initialisation code:

[source,java]
----
import com.tangosol.net.DefaultCacheServer;

public class MyApplication
    {
    public static void main(String[] args)
        {
        // do application initialisation...

        DefaultCacheServer.main(args);
        }
    }
----

or using the non-blocking `startServerDaemon` method:

[source,java]
----
import com.tangosol.net.DefaultCacheServer;

public class MyApplication
    {
    public static void main(String[] args)
        {
        // do application initialisation...

        DefaultCacheServer.startServerDaemon();

        // do more application initialisation...
        }
    }
----


When reviewing the log output, you should see the following two log messages:

[source,log]
----
Coherence gRPC proxy is now listening for connections on 0.0.0.0:1408
Coherence gRPC in-process proxy 'default' is now listening for connections
----

The service is now ready to process requests from one of the Coherence gRPC client implementations.

== Configuration

The default gRPC server will listen for remote connections on port `1408` as well as in-process connections on an
in-process server named `default`.

=== Set the Port

The port the gRPC server listens on can be changed using the `coherence.grpc.server.port` system property,
for example `-Dcoherence.grpc.server.port=7001` will cause the server to bind to port `7001`.

=== Set the In-Process Server Name

The name used by the in-process server can be changed using the `coherence.grpc.inprocess.name` system property,
for example `-Dcoherence.grpc.inprocess.name=foo` will set the in-process server name to `foo`.

=== Advanced gRPC Proxy Server Configuration

It is possible to have full control over the configuration of the server by implementing the interface
`com.oracle.coherence.grpc.proxy.GrpcServerConfiguration`. Implementations of this interface will be loaded
using the Java `ServiceLoader` before the server starts allowing the `ServerBuilder` used to build both the
server and in-process server to be modified.

For example, the class below implements `GrpcServerConfiguration` and configures both servers to use
transport security certificates.

[source,java]
.MyServerConfig.java
----
package com.acme.application;

import com.oracle.coherence.grpc.proxy.GrpcServerConfiguration;

import io.grpc.ServerBuilder;import io.grpc.inprocess.InProcessServerBuilder;

public class MyServerConfig
        implements GrpcServerConfiguration
    {
    public void configure(ServerBuilder<?> serverBuilder, InProcessServerBuilder inProcessServerBuilder)
        {
        File fileCert = new File("/grpc.crt");
        File fileKey  = new File("grpc.key");
        serverBuilder.useTransportSecurity(fileCert, fileKey);
        inProcessServerBuilder.useTransportSecurity(fileCert, fileKey);
        }
    }
----

For the Coherence gRPC proxy to find the above configuration class via the `ServiceLoader` a file named
`com.oracle.coherence.grpc.proxy.GrpcServerConfiguration` needs to be added to application classes `META-INF/services`
directory.

[source]
.com.oracle.coherence.grpc.proxy.GrpcServerConfiguration
----
com.acme.application.MyServerConfig
----

When the gRPC proxy starts it will now discover the `MyServerConfig` and will call it to modify the server builders.

As well as security as in the example, other configuration such as interceptors and even additonal gRPC services can be
added to the server before it starts.

== Disabling the gRPC Proxy Server

As already stated above, the Coherence gRPC server will be started automatically based on `DefaultCacheServer` lifecycle
events. This behaviour can be disabled by setting the `coherence.grpc.enabled` system property to `false`, in which case
a gRPC server will not be started.

== Programmatically starting the gRPC Proxy Server

If the `coherence.grpc.enabled` system property has been set to `false`, the gRPC server can be started manually by
calling the `start()` method on the `GrpcController` singleton instance, for example:

[source,java]
----
import com.oracle.coherence.grpc.proxy.GrpcServerController;

public class MyApplication
    {
    public static void main(String[] args)
        {
        // do application initialisation...

        GrpcServerController.INSTANCE.start();

        // do more application initialisation...
        }
    }
----

The gRPC server can be stopped by calling the corresponding `GrpcServerController.INSTANCE.stop()` method.
