///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////
= Coherence gRPC Server

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.
== Coherence gRPC Server

Coherence gRPC proxy is the server-side implementation of the services defined within the `Coherence gRPC` module.
The gRPC proxy uses standard gRPC Java libraries to provide Coherence APIs over gRPC.

== Usage

In order to use Coherence gRPC Server, you need to declare it as a dependency of your project;
for example if using Maven:

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>{coherence-maven-group-id}</groupId>
  <artifactId>coherence-grpc-proxy</artifactId>
  <version>{version-coherence-maven}</version>
</dependency>
----

or for Gradle:
[source,groovy,subs="attributes+"]
----
implementation '{coherence-maven-group-id}:coherence-grpc-proxy:{version-coherence-maven}'
----

=== Start the Server

The gRPC server will start automatically when `com.tangosol.coherence.net.Coherence` (or `com.tangosol.coherence.net.DefaultCacheServer`) is started.
Typically, `Coherence` will be used as the application's main class, alternatively an instance of `Coherence` can be started using the bootstrap API.

When reviewing the log output, you should see the following two log messages:

[source,log]
----
Coherence gRPC proxy is now listening for connections on 0.0.0.0:1408
Coherence gRPC in-process proxy 'default' is now listening for connections
----

The service is now ready to process requests from one of the Coherence gRPC client implementations.

== Configuration

The default gRPC server will listen for remote connections on port `1408` as well as in-process connections on an
in-process server named `default`.

=== Set the Port

The port the gRPC server listens on can be changed using the `coherence.grpc.server.port` system property,
for example `-Dcoherence.grpc.server.port=7001` will cause the server to bind to port `7001`.

=== Set the In-Process Server Name

The name used by the in-process server can be changed using the `coherence.grpc.inprocess.name` system property,
for example `-Dcoherence.grpc.inprocess.name=foo` will set the in-process server name to `foo`.

=== Using TLS

By default, the gRPC server runs in plaintext mode.
The gRPC server can be configured to use TLS. The relevant key, cert and optional CA files must be provided, either on the classpath of file system.

Assuming that the TLS key is in a file named `/certs/server.key`, and that the server TLS cert is in a file named `/certs/server.pem` then TLS can be configured with the following system properties.

[source]
----
coherence.grpc.server.credentials=tls
coherence.grpc.server.tls.key=/certs/server.key
coherence.grpc.server.tls.cert=/certs/server.pem
----

An optional server key file password can be provided if required, for example if the key file password is `secret`:
[source]
----
coherence.grpc.server.tls.password=secret
----

By default, the server does not require client certificates. The server can be configured to use mutual authentication to verify the client certificates.
[source]
----
coherence.grpc.server.tls.client=REQUIRED
----
The valid values for the `coherence.grpc.server.tls.client` system property are `NONE`, `REQUIRED`, or `OPTIONAL`.

If a CA file is required to verify the client certs it can be provided to the server, for example if the CA file is called `/certs/ca.pem`:
[source]
----
coherence.grpc.server.tls.ca=/certs/ca.pem
----

=== Advanced gRPC Proxy Server Configuration

It is possible to have full control over the configuration of the server by implementing the interface
`com.oracle.coherence.grpc.proxy.GrpcServerConfiguration`. Implementations of this interface will be loaded
using the Java `ServiceLoader` before the server starts allowing the `ServerBuilder` used to build both the
server and in-process server to be modified.

For example, the class below implements `GrpcServerConfiguration` and configures both servers to use
transport security certificates.

[source,java]
.MyServerConfig.java
----
package com.acme.application;

import com.oracle.coherence.grpc.proxy.GrpcServerConfiguration;

import io.grpc.ServerBuilder;
import io.grpc.inprocess.InProcessServerBuilder;

public class MyServerConfig
        implements GrpcServerConfiguration
    {
    public void configure(ServerBuilder<?> serverBuilder, InProcessServerBuilder inProcessServerBuilder)
        {
        File fileCert = new File("/grpc.crt");
        File fileKey  = new File("grpc.key");
        serverBuilder.useTransportSecurity(fileCert, fileKey);
        inProcessServerBuilder.useTransportSecurity(fileCert, fileKey);
        }
    }
----

For the Coherence gRPC proxy to find the above configuration class via the `ServiceLoader` a file named
`com.oracle.coherence.grpc.proxy.GrpcServerConfiguration` needs to be added to application classes `META-INF/services`
directory.

[source]
.com.oracle.coherence.grpc.proxy.GrpcServerConfiguration
----
com.acme.application.MyServerConfig
----

When the gRPC proxy starts it will now discover the `MyServerConfig` and will call it to modify the server builders.

As well as security as in the example, other configuration such as interceptors and even additional gRPC services can be
added to the server before it starts.

== Disabling the gRPC Proxy Server

As already stated above, the Coherence gRPC server will be started automatically based on `DefaultCacheServer` lifecycle
events. This behaviour can be disabled by setting the `coherence.grpc.enabled` system property to `false`, in which case
a gRPC server will not be started.

== Programmatically starting the gRPC Proxy Server

If the `coherence.grpc.enabled` system property has been set to `false`, the gRPC server can be started manually by
calling the `start()` method on the `GrpcController` singleton instance, for example:

[source,java]
----
import com.oracle.coherence.grpc.proxy.GrpcServerController;

public class MyApplication
    {
    public static void main(String[] args)
        {
        // do application initialisation...

        GrpcServerController.INSTANCE.start();

        // do more application initialisation...
        }
    }
----

The gRPC server can be stopped by calling the corresponding `GrpcServerController.INSTANCE.stop()` method.


== Waiting For gRPC Server Start

If you have application code that needs to run only after the gRPC server has started this can be achieved by using
the `GrpcServerController.whenStarted()` method. This method returns a `CompletionStage` that will be completed
when the gRPC server has started.

[source,java]
----
GrpcServerController.INSTANCE.whenStarted().thenRun(() -> {
    // run post-start code...
    System.out.println("The gRPC server has started");
});
----

== Deploy the Proxy Service with Helidon Microprofile gRPC Server

If using the https://helidon.io[Helidon Microprofile server] with the microprofile gRPC server enabled the Coherence
gRPC proxy can be deployed into the Helidon gRPC server instead of the Coherence default gRPC server.

For this behaviour to happen automatically just set the `coherence.grpc.enabled` system property to `false`, which
will disable the built in server. A built-in `GrpcMpExtension` implementation will then deploy the proxy services
to the Helidon gRPC server.

WARNING: When using the Helidon MP gRPC server, if the `coherence.grpc.enabled` system property *has not* been set to
`false`, then both the Helidon gRPC server and the Coherence default gRPC server will start and could cause port
binding issues unless they are both specifically configured to use different ports.


== Manually Deploy the gRPC Proxy Service

If you are running your own instance of a gRPC server and want to just deploy the Coherence gRPC proxy service to this
server then that is possible.

NOTE: If manually deploying the service, ensure that auto-start of the Coherence gRPC server has been disabled by
setting the system property `coherence.grpc.enabled=false`

[source,java]
----
// Create your gRPC ServerBuilder
ServerBuilder builder = ServerBuilder.forPort(port);

// Obtain the Coherence gRPC services and add them to the builder
List<BindableService> services = GrpcServerController.INSTANCE.createGrpcServices()
services.forEach(serverBuilder::addService);

// Build and start the server
Server server = serverBuilder.build();
server.start();
----

