# Copyright 2020, 2025, Oracle Corporation and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence CE GitHub Actions CI build.
# ---------------------------------------------------------------------------

name: Pull Request Build

on:
  pull_request:
    types:
      - opened
      - committed
    branches-ignore:
    - gh-pages
    - p4-integ*
    - last-p4-*

jobs:
  build:
    name: Parallel Build - Linux
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      runner: ubuntu-latest

  examples:
    name: Examples Build
    uses: ./.github/workflows/build-examples.yaml
    secrets: inherit
    with:
      runner: ubuntu-latest
